bratislava/konto.bratislava.sk

next/README.md
next/package.json
next/yarn.lock

Testing github actions on fork

Remove @cloudflare/json-schema-walker

---

next/components/forms/steps/StepperView.tsx
next/components/forms/steps/Summary/SummaryRow.tsx
next/components/ui/FormRJSF/GeneratedFormRJSF.tsx
next/utils/forms.ts

* fix: scrolling in stepper
* fix: not possible to skip to first
* fix: mobile breakpoints
* chore: remove mysterious spamming console log
* fix: scroll problem (tested multiple things but i dont see problems which were sent from testing
* fix: broken skipping of steps because of new skip modal

FROM-306 Stepper mobile fix (#738)

---

next/components/forms/segments/AccountSections/TaxesFeesSection/TaxDetails.tsx
next/public/locales/en/account.json
next/public/locales/sk/account.json

fix translations after change in figma

Form-264/TaxDetails-fix-translations

---

next/components/forms/segments/AccountSections/TaxesFeesSection/PaymentData.tsx
next/public/locales/en/account.json
next/public/locales/sk/account.json

fix 'to pay' button text translation

Form-266/Fix_wording

---

next/components/forms/segments/CorrespondenceAddressModal/CorrespondenceAddressModal.tsx
next/components/forms/widget-components/Modals/Modal.tsx

fix correspondence address modal title, fix modal body mobile padding

Form-352/Modal_Fix

---

next/components/forms/segments/AccountSections/TaxesFeesSection/ContactInformation.tsx
next/components/forms/simple-components/ClipboardCopy.tsx
next/components/styleguide/showcases/SnackbarShowCase.tsx
next/utils/forms.ts
next/utils/useSnackbar.ts

FORM: Fix useSnakbar hook

---

next/components/forms/segments/AccountMarkdown/AccountMarkdown.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFooter.tsx
next/public/locales/en/account.json
next/public/locales/sk/account.json

fix texts, refactor TaxFooter, add to anchor underline-offset-4 in AccountMarkdown

FORM-355: Fix texts after review

---

next/components/forms/segments/UserProfile/UserProfileDetail.tsx
next/components/forms/segments/UserProfile/UserProfileView.tsx
next/pages/bratislava.css

remove eye icon from input password field in Edge/EE browsers, success alert show as snackbar

Form-368/Edge_bugs

---

next/pages/aktivacia-konta.tsx
next/pages/zabudnute-heslo.tsx
next/public/locales/sk/account.json
next/utils/useAccount.tsx

FORM-430 Refresh user data on successful pw reset

---

next/utils/useAccount.tsx

Issues with request headers, see attached screenshots and comment in code.
This will cause all the logged in users to be forcefully logged out - we should be ok with that.

Revert to cognito local storage

---

.github/workflows/deploy.yml
next/.dockerignore
next/Dockerfile
next/next.config.js
next/public/locales/sk/account.json

Update deploy action and Dockerfile

---

next/components/forms/segments/RegisterForm/RegisterForm.tsx
next/frontend/hooks/useAccount.tsx
next/public/locales/sk/account.json

Waiting for change in legal texts which allows this.

New implicit marketing consent flow

---

next/next.config.js

Fix runtime error

---

next/components/forms/segments/HambergerMenu/HamburgerMenu.tsx
next/components/layouts/AccountPageLayout.tsx

Will merge right away to have it checked and deployed once build passes, will be happy for second pair of 👀 and any suggestions (though I know I've probably touched this less than it may deserve)

Fix missing logout in mobile menu

---

next/public/locales/sk/account.json

Update screen Dane. apoplatky (text)

---

next/public/locales/sk/account.json

closes bratislava/private-konto.bratislava.sk#1

#1: update translations "Back to list"

---

next/components/forms/info-components/StatusBar.tsx
next/pages/_app.tsx
next/public/locales/sk/common.json

- add `AlertBannerWrapper` to `_app.tsx` 
- add text to show `AlerBanner`

[#362] add alert banner info

---

next/components/forms/simple-components/ButtonNew.tsx
next/components/forms/simple-components/MLinkNew.tsx
next/components/styleguide/showcases/ButtonNewShowCase.tsx
next/package.json
next/pages/bratislava.css
next/pages/styleguide.tsx
next/tailwind.config.js
next/yarn.lock

Prepared for continuous replacement from old components to these new ones.
TODO: impelment spinner and proper button width in loading state when needed.

implement new Button and Link components

---

next/components/forms/FormStateProvider.tsx
next/components/forms/segments/FormModals/FormModals.tsx
next/components/forms/segments/IdentityVerificationModal/IdentityVerificationModal.tsx
next/components/forms/segments/RegistrationModal/RegistrationModal.tsx
next/components/forms/segments/SkipStepModal/SkipStepModal.tsx
next/components/forms/simple-components/FormHeader.tsx
next/components/forms/simple-components/ModalV2.tsx
next/components/forms/steps/MenuList.tsx
next/components/styleguide/showcases/ModalShowCase.tsx
next/tailwind.config.js

- Create aria Modal
- Replace to use ModalV2 in old modals
- Replace old modal usages

Replace old modals with aria

---

next/clients/axios-instance.ts
next/components/forms/FormPageWrapper.tsx
next/components/forms/segments/UserProfile/UserProfileDetailEdit.tsx
next/components/forms/segments/UserProfile/UserProfileDetailView.tsx
next/components/logic/ServerSideAuthProvider.tsx
next/frontend/utils/amplify.ts
next/pages/mestske-sluzby/[slug]/[id].tsx
next/pages/mestske-sluzby/[slug]/index.tsx

The token handling functionality + showing the page to unauthenticated folks.

#334: Optional auth

---

next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsDraftList.tsx
next/components/forms/steps/Summary/SummaryFiles.tsx
next/components/forms/widget-components/SelectField/SelectFieldNew/ComboBoxNew.tsx
next/components/forms/widget-components/SelectField/SelectFieldNew/SelectFieldNew.tsx

It does not match Figma completely. Just simplified version is implemented. It's up to discussion if Figma version makes sense.
Side fixes:
- fix missing key in SelectItem
- fix route for drafts

#376: implement simple summary files field

---

next/components/forms/groups/DateTimeGroup.tsx
next/components/forms/groups/TimeFromTo.tsx
next/components/forms/widget-components/DateTimePicker/DateField.tsx
next/components/forms/widget-components/DateTimePicker/DateTimeSegment.tsx
next/components/forms/widget-components/DateTimePicker/TimeField.tsx
next/components/forms/widget-components/DateTimePicker/TimePicker.tsx
next/components/forms/widget-components/DateTimePicker/TimeSelector.tsx
next/components/forms/widget-wrappers/TimePickerWidgetRJSF.tsx
next/pages/styleguide.tsx
next/public/locales/sk/account.json

Implement time field using `useTimeField` from react-aria.
There is no support for time picker popup in react-aria, so for now, it is disabled. But I don't think we need picker popup for MVP.

#401: implement TimeFiled with useTimeField (without picker for now)

---

next/components/forms/widget-components/DateTimePicker/TimeField.tsx
next/components/forms/widget-components/FieldBase.ts
next/components/forms/widget-components/SelectField/SelectField.tsx
next/components/forms/widget-components/SelectField/SelectFieldNew/SelectMultiNew.tsx
next/components/styleguide/showcases/SelectMultiNewShowCase.tsx
next/package.json
next/pages/styleguide.tsx
next/public/locales/sk/account.json
next/yarn.lock

TODO
- optionally controlled state
- usage in RJSF

#438: implement new multiple select using react-select

---

next/components/forms/info-components/FieldFooter.tsx
next/components/forms/info-components/FieldHeader.tsx
next/components/forms/widget-components/FieldWrapper.tsx

Does not touch fields which do not use field wrapper, @radoslavzeman should I do anything about those ? Or just create a backlog task ?

#398 Helptext below field in FieldWrapper

---

next/components/forms/FormPageWrapper.tsx
next/components/forms/segments/FormModals/FormModals.tsx
next/components/forms/steps/Summary/SummaryFormControls.tsx
next/components/forms/useFormModals.tsx
next/components/forms/useFormSend.tsx
next/components/forms/useFormState.tsx
next/frontend/utils/formState.ts
next/pages/nases/login.tsx
next/public/locales/sk/forms.json

- Remove duplicate provider
- Form modals fix + comment effects

Form modals fix

---

next/clients/openapi-forms/api.ts
next/components/forms/FormPage.tsx
next/components/forms/FormPageWrapper.tsx
next/frontend/hooks/useFormExportImport.tsx
next/frontend/types/initialFormData.ts
next/pages/mestske-sluzby/[slug]/[id].tsx

- Scroll to top on step change
- Regenerate client
- Fix XML imports/exports, add PDF download

Send eid v3

---

next/components/forms/FormPage.tsx
next/components/forms/FormPageWrapper.tsx
next/components/forms/useFormState.tsx

Might be temporary until better read-only forms - expected to make more here but this gets us to functional state without buttons which don't do any action.

Enable showing sent forms, disable controls for read-only

---

next/components/forms/FormPage.tsx
next/components/forms/useFormErrorTranslations.ts
next/pages/mestske-sluzby/[slug]/[id].tsx
next/public/locales/sk/rjsf-errors.json

see comments in code
likely not extensive, but should provide baseline for adding more errors and adding more error customisation

RJSF Form errors

---

next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
next/components/forms/segments/CookieConsent/CookieConsent.tsx
next/components/forms/simple-components/ButtonNew.tsx
next/components/forms/simple-components/MLinkNew.tsx
next/components/forms/simple-components/ServiceCard.tsx
next/next.config.js
next/package.json
next/pages/_app.tsx
next/yarn.lock

Track clicks on ServiceCards on homepage and "Mestske sluzby" page.
The setup is now same as in bratislava.sk project.

implement custom events for link click, using next-plausible lib

---

next/components/forms/ThemedForm.tsx
next/components/forms/steps/Summary/SummaryForm.tsx
next/components/forms/widget-wrappers/BAObjectFieldTemplate.tsx
next/components/forms/widget-wrappers/CustomComponentsFieldWidgetRJSF.tsx
next/package.json
next/schema-generator/generator/functions.ts
next/schema-generator/generator/uiOptionsTypes.ts

- Remove
- Custom components field
- Add spacing to objects

Custom component field

---

next/components/forms/widget-components/DateTimePicker/DateField.tsx
next/components/forms/widget-components/RadioButton/Radio.tsx
next/components/forms/widget-components/SelectField/SelectField.tsx
next/components/forms/widget-components/SelectField/SelectFieldBox.tsx
next/components/forms/widget-components/TextAreaField/TextAreaField.tsx

Made disabled components' background color consistent 
- changed background color of disabled DatePicker, RadioButton and TextArea to a darker gray.

[#514] Make disabled components background consistent

---

next/components/forms/segments/UserProfile/UserProfileDetailEdit.tsx
next/package.json
next/yarn.lock

- Change phone number validation in `UserProfileDetailEdit.tsx`
- Remove libphonenumber-js packege

[#517] Replace libphonenumber-js phone validation with regex

---

next/components/forms/info-components/Alert.tsx
next/components/forms/steps/StepperViewRow.tsx
next/components/forms/types/Steps.ts
next/components/forms/widget-wrappers/BAArrayFieldTemplate.tsx
next/components/forms/widget-wrappers/SelectFieldWidgetRJSF.tsx
next/frontend/utils/form.ts
next/frontend/utils/formState.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step4.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/vyplnitKrokRadio.ts
next/schema-generator/generator/functions.ts
next/schema-generator/generator/uiOptionsTypes.ts

- Custom stepper title for some steps
- Various improvements

Forms dane

---

next/schema-generator/definitions/shared/investicne.ts

Fix title in schema

---

next/components/forms/ThemedForm.tsx
next/components/forms/steps/Summary/SummaryForm.tsx
next/components/forms/steps/Summary/SummaryWidgetRJSF.tsx
next/components/forms/widget-wrappers/CheckboxGroupWidgetRJSF.tsx
next/components/forms/widget-wrappers/FileUploadWidgetRJSF.tsx
next/components/forms/widget-wrappers/InputWidgetRJSF.tsx
next/components/forms/widget-wrappers/RadioGroupWidgetRJSF.tsx
next/components/forms/widget-wrappers/SelectWidgetRJSF.tsx
next/components/forms/widget-wrappers/TextAreaWidgetRJSF.tsx
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/kalkulacky.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/pravnyVztahSpoluvlastnictvo.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/stavbyBase.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step1.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step2.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step4.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step7.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/vyplnitKrokRadio.ts
next/schema-generator/definitions/shared/investicne.ts
next/schema-generator/definitions/showcase.ts
next/schema-generator/generator/functions.ts
next/schema-generator/generator/uiOptionsTypes.ts

Make consistent and use standardized RJSF widget names
SelectField -> Select
InputField -> Input
RadioButton -> RadioGroup
Checkboxes -> CheckboxGroup
Upload -> FileUpload

Make consistent and use standardized RJSF widget names

---

next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx

- change snackbar translations during concept delete

[#539] change translations during concept delete

---

next/public/locales/sk/account.json

- fix typo in `account_section_services.alert_text`

[bratislava/private-konto.bratislava.sk#31] typo fix

---

next/components/forms/ThemedForm.tsx
next/components/forms/info-components/FieldHeader.tsx
next/components/forms/info-components/FormLightboxModal.tsx
next/components/forms/info-components/FormMarkdown.tsx
next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
next/components/forms/simple-components/LightboxModal.tsx
next/components/forms/steps/Summary/SummaryForm.tsx
next/components/forms/steps/Summary/SummaryWidgetRJSF.tsx
next/components/forms/widget-components/Checkbox/CheckboxGroup.tsx
next/components/forms/widget-components/RadioButton/RadioGroup.tsx
next/components/forms/widget-components/Upload/Upload.tsx
next/components/forms/widget-wrappers/BAObjectFieldTemplate.tsx
next/components/forms/widget-wrappers/CheckboxGroupWidgetRJSF.tsx
next/components/forms/widget-wrappers/CheckboxWidgetRJSF.tsx
next/frontend/utils/form.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/kalkulacky.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step2.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step4.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
next/schema-generator/generator/functions.ts
next/schema-generator/generator/uiOptionsTypes.ts

- Fix button
- Fix spacing in columns
- Improve spacing for field labels
- Helptext in CheckboxGroup
- Form lightboxes
- Fix key
- Checkbox field
- Add ratio format
- Form crazyness

Dane improvements v3

---

next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
next/frontend/api/constants.tsx
next/public/locales/sk/account.json

- add municipal service investing intent tile in MunicipalServicesSections

[bratislava/private-konto.bratislava.sk#10] add municipal service investing intent tile

---

next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
next/frontend/hooks/useFormStateComponents.tsx

- MyApplicationsCard date showing changed
- MyApplicationsCard state icon changed

[bratislava/private-konto.bratislava.sk#36] MyApplicationsCard date condition

---

next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts

Calculator fix

---

.github/workflows/deploy.yml

this is tmp switch to github runners

switched to github-runners

---

next/clients/openapi-forms/api.ts
next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationDetails.tsx
next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationDetailsHeader.tsx
next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
next/components/styleguide/showcases/MyApplicationsCardShowCase.tsx
next/frontend/hooks/useFormStateComponents.tsx
next/frontend/utils/general.ts
next/schema-generator/definitions/shared/investicne.ts

+ updated openAPI code to get frontendTitle from BE
+ fix uiSchema title for SUR forms

[#549] Form title + created/update date from GINIS

---

next/pages/zmena-emailu.tsx
next/public/locales/sk/account.json

- also add back button to email verification screen

Add AliasExistsException error message

---

next/components/forms/info-components/FieldHeader.tsx
next/components/forms/widget-components/Checkbox/CheckboxGroup.tsx
next/components/forms/widget-components/DateTimePicker/DateField.tsx
next/components/forms/widget-components/DateTimePicker/TimeField.tsx
next/components/forms/widget-components/InputField/InputField.tsx
next/components/forms/widget-components/RadioButton/RadioGroup.tsx
next/components/forms/widget-components/SearchField/SearchField.tsx
next/components/forms/widget-components/SelectField/SelectField.tsx
next/components/forms/widget-components/SelectField/SelectFieldNew/SelectMultiNew.tsx
next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
next/components/forms/widget-components/Upload/Upload.tsx
next/components/forms/widget-wrappers/CheckboxGroupWidgetRJSF.tsx
next/components/forms/widget-wrappers/CheckboxWidgetRJSF.tsx
next/components/forms/widget-wrappers/DatePickerWidgetRJSF.tsx
next/components/forms/widget-wrappers/FileUploadWidgetRJSF.tsx
next/components/forms/widget-wrappers/InputWidgetRJSF.tsx
next/components/forms/widget-wrappers/RadioGroupWidgetRJSF.tsx
next/components/forms/widget-wrappers/SelectWidgetRJSF.tsx
next/components/forms/widget-wrappers/TextAreaWidgetRJSF.tsx
next/components/forms/widget-wrappers/TimePickerWidgetRJSF.tsx
next/yarn.lock

- Implement displayOptionalLabel
- Use displayOptionalLabel in forms
- Fix yarn.lock

Display optional label field header

---

next/clients/forms.ts
next/clients/openapi-forms/api.ts
next/components/forms/signer/useFormSignature.tsx
next/components/forms/useFormSend.tsx

Will be glad for feedback on using the controller directly instead of using in useMutation - made sense to me here like that since we are also doing the async signing afterwards, but in case this is not preferred I'll need to be briefed on the mutation usage :)

Signer data from BE, save signature to formData

---

next/components/forms/info-components/FormLightboxModal.module.css
next/components/forms/info-components/FormLightboxModal.tsx
next/components/forms/signer/signerExamplePayload.ts
next/components/forms/signer/signerTypes.ts
next/components/forms/signer/useFormSigner.ts

- Updated example payload
- Use getSignatureWithASiCEnvelopeBase64 for getting signature
- Use tailwind for FormLightboxModal style and add spinner

Dane improvements v11

---

next/components/forms/signer/useFormSignerLoader.tsx
next/components/forms/steps/Summary/SummaryFormSignature.tsx

- Add ability to retry load of DSigner library
- Implement signature properly in summary, texts are not done yet, so hardcoded for now

Dane improvements v12

---

next/components/forms/TaxFormLandingPage.tsx
next/components/forms/segments/AccountMarkdown/AccountMarkdown.tsx
next/components/forms/segments/FormModals/FormModals.tsx
next/components/forms/segments/PropertyTaxCalculator/PropertyTaxCalculator.tsx
next/components/forms/segments/TaxFormPdfExportModal/TaxFormPdfExportModal.tsx
next/components/forms/simple-components/Waves/Waves.tsx
next/components/forms/steps/Summary/SummaryArrayTemplateRJSF.tsx
next/components/forms/steps/Summary/SummaryFormControls.tsx
next/components/forms/useFormModals.tsx
next/components/forms/useFormState.tsx
next/frontend/hooks/useFormExportImport.tsx
next/frontend/types/initialFormData.ts
next/pages/mestske-sluzby/[slug]/[id].tsx
next/pages/mestske-sluzby/priznanie-k-dani-z-nehnutelnosti-dev.ts
next/pages/mestske-sluzby/priznanie-k-dani-z-nehnutelnosti.ts
next/public/locales/sk/forms.json
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts

- Fix translation
- Fix calculator special case
- Fix text
- h2 in markdown
- isTaxForm in initialFormData
- Fix export
- Create tax form landing page feature toggle
- Create temp landing page for tax form
- Create TODO tax form PDF export modal, modify summary controls

Dane improvements v22

---

next/components/forms/TaxFormLandingPage.tsx
next/components/forms/info-components/FieldHeader.tsx
next/components/forms/info-components/FormMarkdown.tsx
next/components/forms/simple-components/ButtonNew.tsx
next/components/forms/useFormModals.tsx
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/osoby.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/pravnyVztahSpoluvlastnictvo.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step1.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step2.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
next/schema-generator/generator/uiOptionsTypes.ts

- Add h5 label size
- Tax year in markdown
- Form changes
- Public page in TaxFormLandingPage
- Make all file upload temporarily optional

Dane improvements v25

---

next/components/forms/TaxFormLandingPage.tsx
next/components/forms/segments/TaxFormPdfExportModal/TaxFormPdfExportModal.tsx
next/components/forms/simple-components/ModalV2.tsx
next/pages/mestske-sluzby/[slug]/[id].tsx
next/pages/mestske-sluzby/priznanie-k-dani-z-nehnutelnosti.ts
next/pages/typography.css
next/public/locales/sk/forms.json

- Temporarily disable signing until online form is ready
- Add modalOverlayClassname to ModalV2.tsx
- Improve route error handling
- Fix tailwind import
- TaxFormPdfExportModal

Dane improvements v26

---

next/public/locales/sk/account.json
next/public/locales/sk/forms.json

- Added periods in the end of texts in snackbars / errors
- https://github.com/bratislava/private-konto.bratislava.sk/issues/2

Add dots in the end of sentence for snackbars and errors

---

next/components/forms/widget-components/Upload/Upload.tsx

- Removed select-non in a upload component
- https://github.com/bratislava/konto.bratislava.sk/issues/699

Remove select-none on upload component

---

next/components/forms/segments/AccountNavBar/AccountNavBar.tsx

- Fixed spacing in navbar between profile name and icons
- https://github.com/bratislava/konto.bratislava.sk/issues/678

Change spacing for profile icons

---

next/components/forms/segments/TaxFormPdfExportModal/TaxFormPdfExportModal.tsx
next/public/locales/sk/forms.json
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts

Dane improvements v27

---

next/components/forms/segments/AccountMarkdown/AccountMarkdown.tsx
next/components/forms/segments/PropertyTaxCalculator/PropertyTaxCalculator.tsx
next/components/forms/segments/TaxFormPdfExportModal/TaxFormPdfExportModal.tsx
next/components/forms/widget-components/RadioButton/RadioGroup.tsx
next/components/forms/widget-wrappers/BAArrayFieldItemTemplate.tsx
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step4.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts

- Fix link
- Fix font size in markdown
- Responsive forms
- Improve calculator messages

Dane improvements v28

---

next/components/forms/widget-wrappers/BAArrayFieldTemplate.tsx
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
next/schema-generator/generator/uiOptionsTypes.ts

- Cannot add item message and improve UI in array
- Form changes

Dane improvements v29

---

next/components/forms/TaxFormLandingPage.tsx
next/components/forms/info-components/TaxFormLandingPageCard.tsx
next/components/forms/simple-components/ButtonNew.tsx
next/public/locales/sk/forms.json

- Fix stretched for unstyled button
- Temp tax form landing page

Dane improvements v30

---

next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
next/components/forms/segments/AccountSectionHeader/AccountSectionHeader.tsx
next/components/forms/segments/AccountSectionHeader/MunicipalServicesSectionHeader.tsx
next/components/forms/segments/AccountSections/HelpSection/HelpSection.tsx
next/components/forms/segments/AccountSections/IntroSection/Announcements/AnnouncementBlock.tsx
next/components/forms/segments/AccountSections/IntroSection/Announcements/Announcements.tsx
next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCard.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesSection.tsx
next/components/forms/segments/UserProfile/UserConsent.tsx
next/components/forms/segments/UserProfile/UserProfileDetailsButtons.tsx
next/components/forms/segments/UserProfile/UserProfileSectionHeader.tsx
next/components/forms/simple-components/Accordion.tsx
next/components/forms/simple-components/Banner.tsx
next/components/forms/simple-components/Brand.tsx
next/components/forms/simple-components/Button.tsx
next/components/forms/simple-components/ServiceCard.tsx
next/components/styleguide/showcases/BannerShowCase.tsx
next/pages/_app.tsx
next/public/locales/sk/account.json

- https://github.com/bratislava/konto.bratislava.sk/issues/324
- Fixed mentioned accessibility issues wrong headers etc.
- Added `focus:ring-2` for specified buttons that have a border
- Added listener and handle to control navigation with keyboard arrows when it gets focused
This two points I couldn't find the issue where it is on the FE (perhaps because I dont have **verified** account?):
- Všeobecné & Daň z nehnuteľností - H3 (I found "Daň z nehnuteľností" but not "Všeobecné" not sure if its the same component)
- Nadpisy akordeónov nie sú označené - dajme ich prosím ako H4 (cant find this at all)

Fix accessibility issues, Add nav controls via keyboard arrows

---

next/components/forms/FormPageWrapper.tsx
next/pages/_app.tsx

- don't track different ids as different pages
- track hash changes

Better tracking of form instances in plausible

---

next/public/locales/sk/common.json

Reverts bratislava/konto.bratislava.sk#754

Revert "Disable status bar about PO registrations"

---

next/components/forms/signer/useFormSignature.tsx

Debug log signature

---

next/frontend/utils/amplify.ts

Revert "Amplify lax cookie"

---

next/components/forms/segments/NavBar/NavBar.tsx

- Revert "Add path in login link in NavBar"

Revert "Add path in login link in NavBar"

---

next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsList.tsx
next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsSection.tsx
next/components/styleguide/showcases/MyApplicationsCardShowCase.tsx
next/pages/moje-ziadosti/index.tsx

- change my-applications-data to fetch from `getServerSideProps`
- change my-applications-data to fetch from react-query

[#608] changed  my-applications-data querying

---

next/clients/openapi-forms/api.ts
next/components/forms/FormPageWrapper.tsx
next/components/forms/FormProviders.tsx
next/components/forms/signer/useFormSignature.tsx
next/components/forms/steps/Summary/FormSummary.tsx
next/components/forms/steps/Summary/SummaryArrayTemplateRJSF.tsx
next/components/forms/steps/Summary/SummaryFiles.tsx
next/components/forms/steps/Summary/SummaryForm.tsx
next/components/forms/steps/Summary/SummaryWidgetRJSF.tsx
next/components/forms/useFormContext.tsx
next/components/forms/useFormFileUpload.tsx
next/components/forms/useFormRedirects.tsx
next/components/forms/useFormSend.tsx
next/components/forms/useFormSent.tsx
next/frontend/hooks/useFormExportImport.tsx
next/frontend/utils/formSignature.ts
next/frontend/utils/getInitialFormSignature.ts
next/package.json
next/pages/mestske-sluzby/[slug]/[id].tsx
next/yarn.lock

Preparations for PDF preview route + save and retrieve form signature properly.

Dane improvements v50

---

next/clients/openapi-forms/api.ts
next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationDetailsHeader.tsx
next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
next/components/forms/useFormContext.tsx
next/components/forms/useFormFileUpload.tsx
next/frontend/hooks/useFormExportImport.tsx
next/frontend/utils/formExportImport.ts
next/frontend/utils/formFileUpload.ts

- Regenerate API client
- Use PDF v2 endpoint

Pdf export v2

---

next/components/forms/steps/Summary/SummaryForm.tsx
next/components/forms/widget-components/FieldBlurWrapper/FieldBlurWrapper.tsx

- Fix disappearing error in forms
- Fix summary spacing in PDF

Dane improvements v55

---

next/clients/openapi-forms/api.ts
next/components/forms/FormPage.tsx
next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationDetailsHeader.tsx
next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
next/frontend/hooks/useFormExportImport.tsx
next/package.json
next/yarn.lock

- useIsomorphicLayoutEffect to supress SSR warnings
- Update @openapitools/openapi-generator-cli
- Regenerate client
- Use new XML/PDF api endpoints

Forms improvements v1

---

next/.env
next/.env.bratiska-cli-build.dev
next/.env.bratiska-cli-build.prod
next/.env.bratiska-cli-build.staging
next/.env.development
next/.env.e2e
next/frontend/utils/formFileUpload.ts

.zip mimetype fix

---

next/components/forms/useFormCurrentStepIndex.ts
next/components/forms/useFormState.tsx
next/package.json
next/yarn.lock

Use nuqs in useFormCurrentStepIndex.ts

---

next/components/forms/segments/NewPasswordForm/NewPasswordForm.tsx
next/components/layouts/AccountPageLayout.tsx
next/frontend/utils/amplifyClient.ts
next/pages/odhlasenie.tsx
next/pages/zabudnute-heslo.tsx

- Create useSignOut
- Fix space
- Add removed clause

#604 update amplify v6 v2

---

next/README.md

Testing GH issues automation
resolves #802

Test GH issues automation 1

---

next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationDetails.tsx
next/public/locales/sk/account.json
next/public/locales/sk/forms.json

Addresses issues:
- #659 
- #590 
- #680 
- #726

Text fixes

---

next/components/forms/TaxFormLandingPage.tsx
next/frontend/utils/amplifyServer.ts
next/pages/mestske-sluzby/[slug]/[id].tsx

multiple fixes

---

next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsSection.tsx

Before: 
https://github.com/bratislava/konto.bratislava.sk/assets/104828482/f989a3a7-ef13-40c9-97c2-41a883b3fcde
After:
https://github.com/bratislava/konto.bratislava.sk/assets/104828482/30913ca3-bc20-4662-8606-2a014a773f02

Tab hover in my application without layout shift

---

tests/cypress/e2e/form/formRegistrationRedirect-mobile.cy.ts
tests/cypress/e2e/form/formRegistrationRedirect.cy.ts
tests/cypress/support/commands/account.ts

fix registration issue

---

next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsList.tsx
next/components/styleguide/showcases/MyApplicationsCardShowCase.tsx
next/frontend/hooks/useFormStateComponents.tsx
next/public/locales/sk/account.json

Introduced by https://github.com/bratislava/nest-forms-backend/pull/378/files
Throws 500 on https://city-account-next.staging.bratislava.sk/moje-ziadosti

Remove READY_FOR_PROCESSING state

---

next/components/forms/segments/PhoneNumberForm/PhoneNumberForm.tsx
next/components/forms/segments/UserProfile/UserProfileDetailEdit.tsx
next/public/locales/sk/account.json

Addresses  https://github.com/bratislava/konto.bratislava.sk/issues/673#issuecomment-2027123709

Modify other phone number fields

---

next/public/locales/sk/common.json

Reverts bratislava/konto.bratislava.sk#934

Revert "Status bar NASES outage 13.4."

---

next/.env.bratiska-cli-build.staging

Add localhost to approved auth origin on staging.

add localhost to approved auth origin on staging

---

next/clients/graphql-strapi/api.ts
next/clients/graphql-strapi/queries/Tax.graphql
next/clients/openapi-tax/api.ts
next/components/forms/segments/AccountSections/IntroSection/Announcements/AnnouncementBlock.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/PaymentData.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFeeSection.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFooter.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCard.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCards.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesDeliveryMethodBanner.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesDeliveryMethodCard.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesDeliveryMethodChangeModal.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesDeliveryMethodDelayed.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesErrorCard.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesInPreparationCard.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesSection.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxFeeSection.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxFeesSection.tsx
next/components/forms/segments/AccountSections/ThankYouSection/ThankYouCard.tsx
next/components/forms/segments/UserProfile/UserProfileConsents.tsx
next/frontend/api/constants.tsx
next/frontend/hooks/useUser.ts
next/pages/dane-a-poplatky/[year].tsx
next/pages/dane-a-poplatky/index.tsx
next/public/locales/sk/account.json

- Create Tax query and regenerate client
- Improve url for verification
- Unify providers for tax pages
- Fetch tax from Strapi
- Integrate TaxesFeesInPreparationCard with Strapi
- Regenerate clients
- Rework useUser -&gt; useUserSubscription
- Fix links
- Change text
- Changes regarding delivery method change

#894 dane 2024 v11

---

next/components/forms/segments/AccountSections/TaxesFeesSection/PaymentData.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCards.tsx
next/public/locales/sk/account.json

- cardPaymentDisabled
- Change condition for displayDeliveryMethodDelayed

#894 Dane 2024 v14

---

next/schema-generator/src/definitions/komunitne-zahrady.ts
next/schema-generator/src/definitions/predzahradky.ts

As discussed in slack thread about these forms.

Modify some titles and helptexts

---

next/.env
next/.env.bratiska-cli-build.dev
next/.env.bratiska-cli-build.prod
next/.env.bratiska-cli-build.staging
next/.env.development
next/.env.e2e
next/components/forms/segments/AccountSectionHeader/TaxFeeSectionHeader.tsx
next/components/forms/segments/AccountSections/IntroSection/Announcements/AnnouncementBlock.tsx
next/components/forms/segments/AccountSections/IntroSection/Announcements/Announcements.tsx
next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/PaymentData.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFeeSection.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesChannelChangeEffectiveNextYearAlert.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCard.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCards.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesDeliveryMethodCard.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesDeliveryMethodChangeModal.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxChannel.tsx
next/environment.ts
next/pages/dane-a-poplatky/[year].tsx
next/pages/index.tsx

- Fix pdfExport display
- Fix spacing for delivery card in tax fee section
- Homepage 2024 tax ready banner
- Remove taxReportDeliveryMethod feature flag
- Fix accessToken type
- Create useTaxChannel to share logic between different tax pages
- Remove comment

#894 Dane 2024 v17

---

next/public/locales/sk/account.json

https://inovaciebratislava.slack.com/archives/C031VRQVA3Z/p1713381083432499

Add error when user is not confirmed and asks for password reset

---

next/components/forms/simple-components/AccordionPaymentSchedule.tsx
next/public/locales/sk/account.json

Change texts for email channel

[#894] Dane 2024 v1

---

next/package.json
next/yarn.lock

Reverts bratislava/konto.bratislava.sk#1028

Revert "Update amplify@6.3.4, @aws-amplify/adapter-nextjs@1.2.1"

---

next/package.json
next/pages/prihlasenie.tsx
next/yarn.lock

https://inovaciebratislava.slack.com/archives/C01RUPRHKTR/p1718289819321259

Revert "Update Amplify to 6.3.6 and handle UserAlreadyAuthenticatedException"

---

nest-forms-backend/Dockerfile

It is not clear for me why chmods are necessary, let @skifahrer resolve it when he comes back.

Copy forms-shared contents instead of using symlinks

---

tests/cypress/e2e/form/formRealEstateTaxReturn.cy.ts

Fix cypress import

---

forms-shared/src/definitions/formDefinitions.ts

](https://inovaciebratislava.slack.com/archives/C031VRQVA3Z/p1720092955001679)

SUR forms message subject fix

---

tests/cypress/e2e/form/formRealEstateTaxReturn.cy.ts

Fix cypress tests: 
- each input must be blurred after typing
- there was .click().click() for continue buttons which is not correct, replaced with .focus().click()

Fix cypress tests

---

forms-shared/src/generator/functions.ts
forms-shared/src/generator/uiOptionsTypes.ts
forms-shared/src/summary-json/SummaryXmlForm.tsx
forms-shared/src/summary-json/getSummaryDisplayValue.ts
forms-shared/tests/__snapshots__/schemas.ts.snap
forms-shared/tests/summary-json/getSummaryDisplayValue.tsx
next/components/forms/ThemedForm.tsx
next/components/forms/widget-wrappers/FileUploadMultipleWidgetRJSF.tsx
next/components/forms/widget-wrappers/NumberWidgetRJSF.tsx
next/components/forms/widget-wrappers/SelectMultipleWidgetRJSF.tsx
next/components/forms/widget-wrappers/createSelectOptionsFromEnumOptions.ts

There were multiple "data types" using same widget which is problematic:
- inside, the widget must decide how to behave based on schema which is risky when something changes
- when generating display value in summary it relied on this ambiguity too
This fixes this.

Form split widget types

---

forms-shared/package-lock.json
forms-shared/package.json
forms-shared/src/definitions/devFormDefinitions.ts
forms-shared/src/form-utils/ajvFormats.ts
forms-shared/src/generator/functions.ts
forms-shared/src/schemas/olo/mimoriadnyOdvozALikvidaciaOdpadu.ts
next/public/locales/sk/rjsf-errors.json

- Add IBAN format
- Mimoriadny odvoz a likvidácia odpadu DEV form

Mimoriadny odvoz a likvidácia odpadu DEV form

---

.github/workflows/validate-and-build.yml

just changing tag from beta to stable as new forms-shared tests are merged in master

moved to stable version

---

forms-shared/src/definitions/devFormDefinitions.ts
forms-shared/src/definitions/formDefinitionTypes.ts
next/.env.bratiska-cli-build.dev
next/.env.bratiska-cli-build.prod
next/.env.bratiska-cli-build.staging
next/.env.development
next/environment.ts
next/frontend/utils/embeddedFormsAllowedOrigins.ts
next/pages/mestske-sluzby/dev/[slug].ts

- Add embedded property to form definition
- Add NEXT_PUBLIC_EMBEDDED_FORMS_OLO_ORIGINS env variable
- getEmbeddedFormsAllowedOrigins utility
- Add Content-Security-Policy frame-ancestors only to dev form route so far

Embedded forms CSP

---

.github/workflows/deploy.yml

thi PR fixes typo in deploy pipeline

fixed typo in scanner name

---

forms-shared/package.json
forms-shared/scripts/sandbox.ts

As it is just a repo containing set of functions I often find myself needing just to execute something, I always create a new file and so on. This just sets this up for quick prototyping.

Create form shared sandbox

---

forms-shared/src/form-utils/ajvFormats.ts
forms-shared/src/generator/functions.ts
forms-shared/src/generator/helpers.ts
forms-shared/src/generator/uiOptionsTypes.ts
forms-shared/src/schemas/olo/mimoriadnyOdvozALikvidaciaOdpadu.ts
forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/osoby.ts
forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/stavbyBase.ts
forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step3.ts
forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step4.ts
forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step5.ts
forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step6.ts
forms-shared/src/schemas/sekcia-uzemneho-rozvoja/surSchemas.ts
forms-shared/src/schemas/shared/fields.ts
forms-shared/src/schemas/ziadostONajomnyByt.ts
forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
forms-shared/tests/form-utils/defaultFormState.ts
forms-shared/tests/form-utils/fileUtils.ts
forms-shared/tests/form-utils/omitExtraData.ts
forms-shared/tests/summary-json/getSummaryDisplayValue.tsx
forms-shared/tests/summary-renderer/validateSummary.ts
next/components/forms/widget-wrappers/InputWidgetRJSF.tsx

As the new form requires "Slovak phone number" not just "phone number", it would be hard in the old input schema definition generation. The details are in commit messages.

Refactor input formats + add Slovak phone number format

---

forms-shared/src/slovensko-sk/file-templates/manifestXml.ts

Fix manifest XML generation based on feedback provided by Gordic

Fix manifest XML generation

---

strapi/schema.graphql
strapi/src/api/form/content-types/form/schema.json
strapi/src/api/form/controllers/form.ts
strapi/src/api/form/routes/form.ts
strapi/src/api/form/services/form.ts
strapi/src/components/blocks/form-landing-page-form-cta.json
strapi/src/components/blocks/form-landing-page-link-cta.json
strapi/src/components/blocks/form-landing-page.json
strapi/types/generated/components.d.ts
strapi/types/generated/contentTypes.d.ts

Form landing pages in Strapi

---

forms-shared/src/generator/uiOptionsTypes.ts
forms-shared/src/schemas/komunitneZahrady.ts
forms-shared/src/schemas/predzahradky.ts
forms-shared/src/schemas/sekcia-uzemneho-rozvoja/surSchemas.ts
forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
next/.env.e2e
next/clients/graphql-strapi/api.ts
next/clients/graphql-strapi/queries/Form.graphql
next/components/forms/FormLandingPage.tsx
next/components/forms/info-components/FormLandingPageCard.tsx
next/components/forms/simple-components/FormHeader.tsx
next/components/forms/useFormContext.tsx
next/frontend/api/constants.tsx
next/pages/mestske-sluzby/[slug]/[id].tsx
next/pages/mestske-sluzby/[slug]/index.tsx
next/pages/mestske-sluzby/dev/[slug].ts
tests/cypress/e2e/form/formRegistrationRedirect-mobile.cy.ts
tests/cypress/e2e/form/formRegistrationRedirect.cy.ts
tests/cypress/e2e/form/formSIZ.cy.ts
tests/cypress/e2e/form/formSummaryCheck.cy.ts
tests/cypress/e2e/form/formZSIZ.cy.ts
tests/cypress/e2e/registration/registrationModalSIZ.cy.ts
tests/cypress/e2e/registration/registrationModalZSIZ.cy.ts

`FormLandingPage` + card copied mostly from `TaxFormLandingPage`

Landing pages strapi v3

---

forms-shared/package-lock.json
forms-shared/package.json
forms-shared/scripts/createAiPrompt.ts

An utility script that merges all schemas and UI options (really helps the UI to generate the file) to one file that can be used for prompting.

Create AI prompt utility

---

next/components/forms/widget-wrappers/BAObjectFieldTemplate.tsx

Accidentally commited here - https://github.com/bratislava/konto.bratislava.sk/commit/a3e0a3f521f6bb5434c95ad132eb8168c7ef14b9

Remove schema.title display in BAObjectFieldTemplate

---

forms-shared/src/definitions/formDefinitionTypes.ts
forms-shared/src/definitions/formDefinitions.ts
nest-forms-backend/src/ginis/ginis.service.ts

Reverts bratislava/konto.bratislava.sk#1384

Revert "Change Ginis assignee, allow ginis org name without person"

---

forms-shared/src/definitions/formDefinitionTypes.ts
forms-shared/src/definitions/formDefinitions.ts
nest-forms-backend/src/ginis/ginis.service.ts

Reverts bratislava/konto.bratislava.sk#1385

Revert "Revert "Change Ginis assignee, allow ginis org name without person""

---

next/components/forms/segments/AccountSections/IntroSection/Announcements/Announcements.tsx
next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
next/frontend/constants/constants.tsx
next/public/locales/sk/account.json

- add `Žiadosť o nájom bytu` to `IntroSection` and change other shown services
- add link to `Žiadosť o nájom bytu` to `MunicipalServicesSection`
- add new category `Sociálne služby a bývanie` to `MunicipalServicesCategories`

[#1299] add links to rental service application

---

nest-forms-backend/Dockerfile

This PR removes git install from forms dockerfile

removed git from docker file

---

nest-forms-backend/src/nases/nases.service.spec.ts
nest-forms-backend/src/nases/nases.service.ts

Local fix + test.
Without this user gets no feedback when sending to NASES fails if they are using eID approach.

When sending with eId, let user know immediately in case of NASES error

---

.github/dependabot.yml
.github/workflows/validate-and-build.yml

After previous setting was tested, this improves the permissions and make it more job specific.

updated permissions on pipelines to make it run for depenadbot

---

.github/workflows/cluster-deploy-conditions-konto.yml
README.md

- fixed job name which prevents nest-tax-backend to be depoyed to staging
- added to tax backend to readme
- small typoos were fixed too

Staging pipeline bugfix for nest-tax-backend

---

next/components/forms/FormPage.tsx
next/components/forms/FormPageWrapper.tsx
next/components/forms/IframeResizerChild.tsx
next/components/forms/simple-components/ModalV2.tsx

Unforunately all this work was needed to display the modals correctly when in iframe
https://github.com/user-attachments/assets/0289a87d-5e28-4233-a637-897c65ad190c

Special modal positioning when the page is in iframe

---

forms-shared/src/summary-email/SummaryEmail.tsx

I told Claude Sonnet to fix the rendering in Outlook and fortunately it worked.
Before:
After:

Fix rendering of emails in Outlook

---

.github/workflows/validate-and-build.yml

fixed wrong folder on validate nest-tax-backend

---

forms-shared/src/definitions/formDefinitionTypes.ts
forms-shared/src/definitions/formDefinitions.ts
forms-shared/src/schemas/olo/docisteniStanovistaZbernychNadob.ts
forms-shared/src/schemas/olo/koloTaxi.ts
forms-shared/src/schemas/olo/mimoriadnyOdvozAZhodnotenieOdpadu.ts
forms-shared/src/schemas/olo/odvozObjemnehoOdpaduValnikom.ts
forms-shared/src/schemas/olo/odvozOdpaduVelkokapacitnymAleboLisovacimKontajnerom.ts
forms-shared/src/schemas/olo/oloTaxi.ts
forms-shared/src/schemas/olo/podnetyAPochvalyObcanov.ts
forms-shared/src/schemas/olo/shared/zevoShared.ts
forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPrePravnickeOsoby.ts
forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPreSpravcovskeSpolocnosti.ts
nest-forms-backend/src/nases-consumer/nases-consumer.service.ts
nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
next/components/forms/serializableFormDefinition.ts
next/components/forms/useFormContext.tsx
next/pages/forms-playground.ts
next/pages/mestske-sluzby/[slug]/[id].tsx
next/pages/mestske-sluzby/dev/[slug].ts

- Rename <code>toEmail</code> to <code>userEmail</code> and <code>firstName</code> to <code>userFirstName</code>
- Rename <code>userEmailPath</code> to <code>extractEmail</code> and <code>userNamePath</code> to `extra…
- Implement email and name extractions in form definitions
- Implement email and name extractions in EmailFormsSubservice

OLO extract email and name from user data

---

forms-shared/scripts/createAiPrompt.ts
forms-shared/src/definitions/formDefinitions.ts
forms-shared/src/schemas/tsb/objednavkaVytycenie.ts
forms-shared/src/schemas/tsb/objednavkaZakresuSieti.ts
forms-shared/src/schemas/tsb/umiestnenieZariadenia.ts
forms-shared/src/schemas/tsb/ziadostOStanoviskoPD.ts
forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
forms-shared/tests/definitions/formDefinitions.ts

Did not check the forms too closely, only fixed the obvious mistakes from ai gen.
Would like to make these send-able on staging so that we may test the webhooks - @MarekBodinger from what I understand, I need to have them outside of devFormDefinitions and in regular formDefinitions to do that.

TSB forms v1

---

next/components/forms/segments/AccountSections/ThankYouSection/ThankYouCard.tsx
next/components/forms/segments/AccountSections/ThankYouSection/ThankYouFormSection.tsx
next/public/locales/sk/account.json

This page / card / section implementation is broken, I created `useThankYouFormSection` the hook to return the correct props instead of getting them directly in TSX template, but this needs rework anyway.

Implement thank you page for embedded forms

---

nest-forms-backend/src/convert/convert.controller.ts

Adding this temporarily so that we can see the issue before more logging is available on this service.

Log data of xml conversion on errors

---

nest-tax-backend/src/tasks/tasks.service.ts

Type casting needed to be used.

fix: raw query in tax backend fix

---

next/.env
next/.env.bratiska-cli-build.dev
next/.env.bratiska-cli-build.prod
next/.env.bratiska-cli-build.staging
next/.env.development
next/.env.e2e
next/components/forms/FormsIframeTestPage.tsx
next/environment.ts
next/frontend/utils/embeddedFormsHelpers.ts
next/package-lock.json
next/package.json
next/pages/forms-iframe-test.ts

It's cumbersome to test the iframe resizing / embedding on two running servers, this also makes the implementation no tied to external page (= if it works here, it should work everywhere).

Forms Iframe test page

---

nest-tax-backend/kubernetes/base/kustomization.yml
nest-tax-backend/src/tasks/tasks.service.ts

This is to patch the failing database. I'd like to keep the timeout and logging in, but we can discuss the intervals (of timeout and the cron itself) next week.

Make tax sum query timeout, temporarily increase interval

---

next/components/forms/segments/CookieConsent/CookieConsent.tsx
next/pages/_app.tsx
next/pages/mestske-sluzby/[slug]/[id].tsx
next/pages/mestske-sluzby/dev/[slug].ts

Disables Hotjar on externally embedded pages.
Fixes https://github.com/bratislava/olo.sk/issues/844

OLO disable Hotjar

---

nest-tax-backend/kubernetes/envs/Dev/.env
nest-tax-backend/kubernetes/envs/Prod/.env
nest-tax-backend/kubernetes/envs/Staging/.env
nest-tax-backend/src/utils/subservices/qrcode.subservice.ts
next/components/forms/segments/AccountSections/TaxesFeesSection/PaymentData.tsx
next/public/locales/sk/account.json

- Remove constant symbol from tax payment data on FE
- Remove constant symbol from payment QR code

#1538 Tax remove constant symbol

---

next/components/forms/segments/FormModals/FormModals.tsx

Fix "A props object containing a "key" prop is being spread into JSX" error

---

nest-forms-backend/src/tax/tax.controller.ts

Copied from here: https://github.com/bratislava/konto.bratislava.sk/blob/7a2eeaff1d90c6f889822b45f34d2fd7cfd2bc1d/nest-forms-backend/src/convert/convert.controller.ts#L101

Log get signer data error

---

nest-forms-backend/src/convert/convert.service.ts
nest-forms-backend/src/nases/utils-services/tokens.nases.service.spec.ts
nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts

Cannot link via development: 
https://github.com/bratislava/private-konto.bratislava.sk/issues/50

Attach summary PDF to tax form Slovensko.sk message

---

next/components/forms/FormLandingPage.tsx
next/public/locales/sk/forms.json

Fix translations after https://github.com/bratislava/konto.bratislava.sk/pull/1823/

Fix translations after "Remove temporary tax form landing page"

---

nest-tax-backend/src/utils/subservices/qrcode.subservice.ts

#1435 add QR_WEB message to qr-code payments

---

next/components/forms/segments/NavBar/NavBar.tsx
next/components/layouts/AccountPageLayout.tsx
next/pages/dane-a-poplatky/index.tsx

For SZCO and PO:
- Hide taxes section in navbar
- Redirect to 404 on /dane-a-poplatky

1232: Hide taxes section for legal entities

---

.github/ISSUE_TEMPLATE/technical-issue

As agreed on slack, open to changes.

Create technical-issue template

---

next/components/forms/segments/AccountSections/TaxesFeesSection/ContactInformation.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFeeSection.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxFeeSection.tsx
next/pages/dane-a-poplatky/[year].tsx
next/public/locales/sk/account.json

Cannot link for some reason:
https://github.com/bratislava/konto.bratislava.sk/issues/1833

#1833 Tax administrator contact card

---

next/components/forms/segments/AccountMarkdown/AccountMarkdown.tsx
next/components/forms/steps/Summary/SummaryAdditionalInfo.tsx
next/components/forms/steps/Summary/SummaryFormLegalText.tsx

Fix summary markdown sizing

---

nest-forms-backend/src/common/utils/city-account.ts

https://github.com/bratislava/private-konto.bratislava.sk/issues/55

Comment verifyUserByEidToken

---

next/components/forms/segments/AccountSections/ThankYouSection/ThankYouCard.tsx
next/components/forms/segments/AccountSections/ThankYouSection/ThankYouFormSection.tsx
next/components/forms/segments/TaxFormPdfExportModal/TaxFormPdfExportModal.tsx
next/frontend/constants/constants.tsx
next/public/locales/sk/account.json

Modify the feedback button after downloading pdf/sending DP

1689: Modify feedback button DP

---

nest-forms-backend/Dockerfile
nest-forms-backend/package.json
nest-forms-backend/prisma/migrations/20250110152852_add_form_summary/tsconfig.json

- Fix migrate add for summary run

Fix migrate add for summary run

---

forms-shared/package-lock.json
forms-shared/package.json
forms-shared/src/definitions/devFormDefinitions.ts
forms-shared/src/generator/createCombinations.ts
forms-shared/src/generator/functions/conditionalStep.ts
forms-shared/src/generator/helpers.ts
forms-shared/src/schemas/oznamenieOVznikuZmeneAleboZanikuPoplatkovejPovinnosti.ts
nest-forms-backend/package-lock.json
next/package-lock.json

- Add description and stepperTitle to conditionalStep
- Fix createCondition type
- Add createCombinations
- Install ts-pattern
- Force variant in RadioGroupUiOptions
- Create oznamenieOVznikuZmeneAleboZanikuPoplatkovejPovinnosti dev form

1984 Komunal form first version

---

.github/workflows/validate-nest-prisma-konto.yml

It probably broke some threshold here:
https://github.com/bratislava/konto.bratislava.sk/actions/runs/12908643884/job/35994899697

Increase heap size for unit tests

---

README.md

Some polishing before /docs is added:
- added summary of whats in repo
- removed most fluff (if we want it we should have it org level)
- alphabetical ordering of subdirs
- simplified language in deployments

Polish root README

---

nest-forms-backend/src/main.ts

When uploading large XMLs in forms import XML it throws:

Fix PayloadTooLargeError

---

docs/runbook/formulare-support.md

See commit names. "Forms support corrections" is just grammar, with one exeption, but I need feedback on that line from @lukasbabula either way - see comment on code below.

Forms support runbook edits

---

nest-tax-backend/src/admin/__tests__/admin.service.spec.ts
nest-tax-backend/src/admin/admin.service.ts
nest-tax-backend/src/utils/subservices/cityaccount.subservice.ts

Moved throwerErrorGuard to constructors.

ThrowerErrorGuard was not injected properly

---

next/components/forms/segments/AccountSections/ThankYouSection/ThankYouCard.tsx
next/components/forms/segments/AccountSections/ThankYouSection/ThankYouSection.tsx
next/frontend/constants/constants.tsx
next/public/locales/sk/account.json

Similar change as in tax form thank you modal
Tested thank you cards for:
- tax form
- other form
- olo form
they look the same as on master (nothing is broken)

1691: Add new feedback button to thankyou page after card payment

---

.vscode/settings.json
nest-city-account/.env.example
nest-city-account/docker-compose.yml
nest-city-account/package-lock.json
nest-city-account/package.json
nest-city-account/src/user-verification/verification.module.ts
nest-city-account/tsconfig.json

See commit names.
+ there's an issue with the way we have this setup, due to which if an error happens during startup we don't see it but see the app hanging indefinitely. Will create an issue.
While hunting for that and before finding out it was a missing env, found that the @golevelup/nestjs-rabbitmq at the version we were says it is not supporting nestjs >= 10, updated along the way.

City-account - udate example .env and rabbitmq library

---

nest-forms-backend/kubernetes/envs/Dev/.env
nest-forms-backend/kubernetes/envs/Prod/.env
nest-forms-backend/kubernetes/envs/Staging/.env

https://github.com/bratislava/private-konto.bratislava.sk/issues/782

Remove unused FOP_BRATISLAVA_API

---

docs/runbook/formulare-support.md

Also unify unordered list style and enhance on checking form logs to determine rabbit queue presence.

Add missing information about attachment skip to form support runbook

---

next/public/locales/sk/forms.json

https://github.com/bratislava/private-konto.bratislava.sk/issues/783

783 Versioning texts improvements

---

nest-forms-backend/kubernetes/envs/Prod/.env
next/.env.bratiska-cli-build.prod

https://github.com/bratislava/private-konto.bratislava.sk/issues/98

Turn on versioning in production

---

forms-shared/src/example-forms/examples/ziadostONajomBytuExample.ts
forms-shared/src/sharepoint/mappings/ziadostONajomBytu.ts
forms-shared/tests/sharepoint/__snapshots__/getValuesForSharepoint.ts.snap

Adds KontaktovanyEmailom to the main card

add KontaktovanyEmailom field to main Sharepoint card

---

forms-shared/src/definitions/formDefinitions.ts

https://github.com/bratislava/private-konto.bratislava.sk/issues/721

721 Change send policy for Žiadosť o nájom bytu

---

forms-shared/src/definitions/formDefinitions.ts
nest-forms-backend/src/utils/handlers/text.handler.spec.ts
nest-forms-backend/src/utils/handlers/text.handler.ts

https://github.com/bratislava/private-konto.bratislava.sk/issues/859

Very temporary fix for SUR forms subject

---

next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx

https://github.com/bratislava/private-konto.bratislava.sk/issues/864

Remove tax card for PO

---

forms-shared/src/definitions/formDefinitions.ts

https://github.com/bratislava/private-konto.bratislava.sk/issues/873

Fix ginis document assignment for garden forms

---

nest-forms-backend/.env.example
nest-forms-backend/kubernetes/envs/Dev/.env
nest-forms-backend/kubernetes/envs/Prod/.env
nest-forms-backend/kubernetes/envs/Staging/.env
nest-forms-backend/package-lock.json
nest-forms-backend/package.json
nest-forms-backend/src/config/ba-config.ts
nest-forms-backend/src/config/environment-variables.ts
nest-forms-backend/src/ginis/ginis.service.spec.ts
nest-forms-backend/src/ginis/ginis.service.ts
nest-forms-backend/src/ginis/subservices/ginis-api.service.spec.ts
nest-forms-backend/src/ginis/subservices/ginis-api.service.ts

Another huge step in the direction of replacing ginis automation.

833 Replace ginis automation register functionality with ginis api

---

next/public/locales/sk/common.json

This reverts commit 43fcbb1d77cf7326b7fef0202875c241c268b0c2.

Revert "add statusBarContent (#2770)"

---

nest-city-account/src/user-verification/utils/subservice/verification.subservice.ts
nest-city-account/src/user-verification/verification.controller.ts
nest-city-account/src/user-verification/verification.service.ts
nest-city-account/src/utils/subservices/line-logger.subservice.ts

This PR reverts a temporary commit that improved logging and formatting for verification processes. The original changes were intended to be reverted before release but were mistakenly merged.

Revert logging and formatting improvements

---

strapi/schema.graphql
strapi/src/api/homepage-announcement/content-types/homepage-announcement/schema.json
strapi/src/api/homepage-announcement/controllers/homepage-announcement.ts
strapi/src/api/homepage-announcement/routes/homepage-announcement.ts
strapi/src/api/homepage-announcement/services/homepage-announcement.ts
strapi/src/api/homepage/content-types/homepage/schema.json
strapi/src/api/homepage/controllers/homepage.ts
strapi/src/api/homepage/routes/homepage.ts
strapi/src/api/homepage/services/homepage.ts
strapi/src/api/municipal-service-category/content-types/municipal-service-category/schema.json
strapi/src/api/municipal-service-category/controllers/municipal-service-category.ts
strapi/src/api/municipal-service-category/routes/municipal-service-category.ts
strapi/src/api/municipal-service-category/services/municipal-service-category.ts
strapi/src/api/municipal-service/content-types/municipal-service/schema.json
strapi/src/api/municipal-service/controllers/municipal-service.ts
strapi/src/api/municipal-service/routes/municipal-service.ts
strapi/src/api/municipal-service/services/municipal-service.ts
strapi/src/api/municipal-services-page/content-types/municipal-services-page/schema.json
strapi/src/api/municipal-services-page/controllers/municipal-services-page.ts
strapi/src/api/municipal-services-page/routes/municipal-services-page.ts
strapi/src/api/municipal-services-page/services/municipal-services-page.ts
strapi/types/generated/contentTypes.d.ts

https://github.com/bratislava/private-konto.bratislava.sk/issues/83
https://github.com/bratislava/private-konto.bratislava.sk/issues/896

Strapi types for municipal services and announcements

---

nest-tax-backend/src/noris/__tests__/noris.service.spec.ts
nest-tax-backend/src/noris/noris.service.ts

Another approach to try and lower the number of errors during noris tax update. The error message is:
`causedByMessage="Connection not yet open."`
Also try to create a function to create connections, as this can be modified furthermore, instead of replicating the same code multiple times. First it has to be tested on the tax update though.

Wait for connection on noris tax update

---

next/backend/utils/strapi-tax-administrator.ts
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFeeSection.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCards.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesTaxAdministratorCard.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxFeeSection.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxFeesSection.tsx
next/pages/dane-a-poplatky/[year].tsx
next/pages/dane-a-poplatky/index.tsx

https://github.com/bratislava/private-konto.bratislava.sk/issues/885

885 Tax administrator from Tax BE

---

nest-city-account/.env.example
nest-city-account/kubernetes/envs/Dev/.env
nest-city-account/kubernetes/envs/Prod/.env
nest-city-account/kubernetes/envs/Staging/.env
nest-clamav-scanner/.env.example
nest-clamav-scanner/kubernetes/envs/Dev/.env
nest-clamav-scanner/kubernetes/envs/Prod/.env
nest-clamav-scanner/kubernetes/envs/Staging/.env
nest-tax-backend/.env.example
nest-tax-backend/kubernetes/envs/Dev/.env
nest-tax-backend/kubernetes/envs/Prod/.env
nest-tax-backend/kubernetes/envs/Staging/.env

https://github.com/bratislava/private-konto.bratislava.sk/issues/841

#841: add cluster enviroment info to all backend projects

---

nest-forms-backend/src/config/environment-decorators.ts
nest-forms-backend/src/config/environment-variables.ts
nest-forms-backend/src/config/environment-variables.validate.ts

https://github.com/bratislava/private-konto.bratislava.sk/issues/982

982 Fix form validated config boolean parsing

---

nest-forms-backend/src/utils/subservices/sharepoint.subservice.ts

https://stackoverflow.com/questions/77935301/updating-a-lookup-field-in-sharepoint-via-microsoft-graph-api-results-in-invali
https://github.com/bratislava/private-konto.bratislava.sk/issues/1009

Fix: sending lookup fields to sharepoint list

---

openapi-clients/package-lock.json
openapi-clients/package.json

https://www.aikido.dev/blog/npm-debug-and-chalk-packages-compromised

Update chalk to version with a fix for previous vulnerability

---

nest-tax-backend/kubernetes/envs/Dev/kustomization.yml
nest-tax-backend/kubernetes/envs/Dev/secrets/admin.secret.yml

- add missing api key in nest-tax-backend to nest-city-account

add missing api key in nest-tax-backend to nest-city-account
