bratislava/konto.bratislava.sk

next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx

I used userData && !userData?.phone_number in condition, userData need to be here on the start, it doesn't work without it

FORM-345: Mobile phone modal - fix render only when user doesn-t have mobile data

---

next/components/forms/info-components/StatusBar.tsx
next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
next/components/forms/segments/AccountSectionHeader/AccountSectionHeader.tsx
next/components/forms/segments/AccountSectionHeader/MunicipalServicesSectionHeader.tsx
next/components/forms/segments/AccountSectionHeader/TaxFeeSectionHeader.tsx
next/components/forms/segments/LoginRegisterNavBar/LoginRegisterNavBar.tsx
next/components/layouts/AccountPageLayout.tsx
next/components/layouts/LoginRegisterLayout.tsx
next/components/styleguide/showcases/StatusBarShowCase.tsx
next/pages/_app.tsx
next/pages/form/[eform].tsx
next/pages/styleguide.tsx

First part of the task - a status bar for displaying various errors. WIll be used to warn the user about failed verification. DIsplays on top of the page header.
Slightly simplified the mobile account header styling while at this, as it got in the way. Recommended to check the changes with "hide whitespace changes" toggled in github.
Edit: also changed the header behaviour - now that the height is dynamic, dealing with the offset of the rest of the content in the header itself + removed the static offsets from the rest of the sectiosn (please let me know if I missed any)

FROM-331: StatusBar component on top of the page

---

next/.env.bratiska-cli-build.dev
next/.env.bratiska-cli-build.prod
next/.env.bratiska-cli-build.staging
next/.env.development
next/components/forms/segments/IdentityVerificationForm/IdentityVerificationForm.tsx
next/components/forms/segments/RegisterForm/RegisterForm.tsx
next/package.json
next/pages/register.tsx
next/utils/api.ts
next/utils/useAccount.tsx
next/yarn.lock

- turnstile validates in lambda on cognito pre-signup hook (this is already true) and on backend identity verification (this will be true soon)
- contains an unrelated ugly fix for when emailverificationsuccess statew was immediately overwritten in response from user login - this workaround should be replaced very soon (🤞 ) together with moving the accountstatus out of the hook into a more localized state

Add Turnstile captcha, fix EmailVerificationSuccess status

---

next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx

- modal kept hidden after it's dismissed once - was being previously displayed on userData refresh

FROM-435: Phone number modal issues

---

next/components/forms/info-components/FieldErrorMessage.tsx
next/public/locales/en/account.json
next/public/locales/en/forms.json
next/public/locales/sk/account.json
next/public/locales/sk/forms.json

I changed the FieldErrorMessage because everything but the first letter will be in lower case. I don't think we want that. In my case, the error in the InputField looked like +421xxxxxxxxx, but it should be +421XXXXXXXXX.

FORM-436: Change phone helpText in phone modal, edit FieldErrorMessage

---

next/frontend/hooks/useAccount.tsx
next/pages/sso.tsx
next/public/locales/sk/account.json

Ended up dropping the useAccount rewrite for now (I know I've been talking about it for a while), in the end what we really need in the other projects authenticating through city account is not shared account hook but rather something like this - the ability for approved domains to:
a) redirect to city-account page when user is not logged in and let the user login/register within existing flow (not covered here) and 
b) let the approved domains open city-account in an invisible webview (will be covered in other projects) and receive an access token which they can store and use to access backend resources until it expires (after which point, they can ask for another one in the same manner)
🙏 will be glad to receive any feedback on this - though I may merge it beforehand to allow testing …

SSO: share JWT accessToken to approved domains via postMessage

---

next/frontend/hooks/useAccount.tsx
next/frontend/utils/sso.ts
next/pages/logout.tsx
next/pages/prihlasenie.tsx
next/pages/registracia.tsx
next/public/locales/sk/account.json

This is needed so that a user may come from another site which uses city-account just as a single sign-on "host", do what he needs and be redirected back where they came from.
Added a logout page so that user confirms he's logging out from everywhere (also a CSRF measure compared to just logging out on visiting the url).

SSO: register/login/logout redirects

---

next/frontend/hooks/useSSORedirect.tsx
next/pages/_app.tsx
next/pages/logout.tsx
next/pages/prihlasenie.tsx
next/pages/registracia.tsx

What this solves: when the user comes to login/register with a `from` query to which they should be redirected afterwards, but they don't complete the initial flow (i.e., they land on login, but instead go to registration), we still want to redirect them back the moment they succesfully login or create the account.

Redirect target persisted between page reloads

---

next/.eslintrc.js
next/backend/utils/forms.ts
next/components/forms/FormStateProvider.tsx

- Remove comment
- Revert "Warn for @typescript-eslint/no-unused-vars"
- Fix eslint

Forms refactor 1 fix

---

next/components/forms/steps/Summary/FormSummary.tsx
next/components/forms/steps/Summary/SummaryFieldRJSF.tsx
next/components/forms/steps/Summary/SummaryWidgetRJSF.tsx
next/components/forms/widget-components/FieldBase.ts
next/components/forms/widget-wrappers/CheckboxWidgetRJSF.tsx
next/components/forms/widget-wrappers/DatePickerWidgetRJSF.tsx
next/components/forms/widget-wrappers/InputFieldWidgetRJSF.tsx
next/components/forms/widget-wrappers/RadioButtonWidgetRJSF.tsx
next/components/forms/widget-wrappers/SelectFieldWidgetRJSF.tsx
next/components/forms/widget-wrappers/TextAreaFieldWidgetRJSF.tsx
next/components/forms/widget-wrappers/TimePickerWidgetRJSF.tsx
next/components/forms/widget-wrappers/UploadWidgetRJSF.tsx
next/components/forms/widget-wrappers/fieldGroupsRJSF/DateFromToWidgetRJSF.tsx
next/components/forms/widget-wrappers/fieldGroupsRJSF/DateTimeWidgetRJSF.tsx
next/components/forms/widget-wrappers/fieldGroupsRJSF/TimeFromToWidgetRJSF.tsx

The styling is inconsistent - created a followup (draft) task for that here  - https://github.com/orgs/bratislava/projects/6/views/5?pane=issue&itemId=39605991
Otherwise should be functioning. Disabled === readonly afaik, let me know if there should be a difference in behaviour. I did not see the `readonly` prop being used in SummaryForm (despite it always being set), so I've used it for conditionally (not) displaying the edit button in readonly forms - would also like to check about this, whether I did not break something unexpected.

Read only fields

---

next/components/forms/segments/AccountSectionHeader/MunicipalServicesSectionHeader.tsx
next/components/forms/widget-components/SelectField/Dropdown.tsx
next/components/forms/widget-components/SelectField/DropdownRow.tsx
next/components/forms/widget-components/SelectField/SelectField.tsx
next/components/forms/widget-components/SelectField/SelectFieldBox.tsx
next/components/forms/widget-wrappers/SelectWidgetRJSF.tsx
next/schema-generator/generator/uiOptionsTypes.ts

- Trim text in the select dropdown rows at the end of the line instead of after an arbitrary number of characters
- The selected line is displayed whole

[#600] Trim text at the end of line

---

next/components/forms/info-components/Alert.tsx
next/components/forms/segments/UserProfile/UserProfileDetail.tsx
next/components/forms/segments/UserProfile/UserProfileSectionHeader.tsx

- Moved alert to be outside of profile header and appear according to Figma. 
- Changed padding of alert text on mobile
- https://github.com/bratislava/konto.bratislava.sk/issues/681

Move non verified alert outside of user profile header

---

next/pages/api/robots.ts

With this only /mestske-sluzby/priznanie-k-dani-z-nehnutelnosti-dev are no longer indexed on production, the rest of the pages reachable through urls (from bratislava.sk) should slowly appear.

Allow searchengines on production

---

next/components/forms/useFormFileUpload.tsx
next/components/forms/widget-components/Upload/UploadFileCard.tsx
next/frontend/types/formFileUploadTypes.ts
next/frontend/utils/formFileUpload.ts
next/public/locales/sk/account.json

- https://github.com/bratislava/nest-forms-backend/issues/234
- Added custom error message for not finding form to which user tries to upload file
- Also added custom error message for when file has size zero
- Possibility to add other custom errors, based on BE response message `errorName`

Add custom errors for uploaded files in forms

---

next/components/forms/FormPageWrapper.tsx

Found out even manually tracked pageview events go through the same filter which omits any /mestske-sluzby/*/* views. This tracks these custom pageviews on /mestskesluzby/slug#step instead.

Fix plausible views on form pages

---

next/frontend/dtos/accountDto.ts

The rest of the setup is on cognito site.
The type is string (can be only string or number in cognito), the expected usage is to treat it as bool/flag.

Custom cognito tax form beta attribute

---

next/components/forms/useFormSend.tsx
next/components/styleguide/showcases/MyApplicationsCardShowCase.tsx

This got renamed on BE (the old field is deprecated) and never made it's way to FE until now.

Form data base64

---

next/kubernetes/envs/Prod/scaler.yml

* Lower rolling window on Prometheus queries for KEDA autoscaler, because `10m` smoothed rapidly fluctuating metrics a bit too much and no upscaling was performed
* Change final `sum` to `max` function to scale no matter what pod is hitting the limit (they don't have to hit it on average)

fix: KEDA scaller when metric is fluctuating

---

next/components/forms/widget-wrappers/BAArrayFieldItemTemplate.tsx
next/components/forms/widget-wrappers/BAObjectFieldTemplate.tsx
next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/osoby.ts
next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/stavbyBase.ts
next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/step3.ts
next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/step4.ts
next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/step5.ts
next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/step6.ts
next/schema-generator/definitions/shared/investicne.ts
next/schema-generator/generator/uiOptionsTypes.ts

Although I don't like to change the UI options this is a must.
Decouple whether object displays columns and display type in objects to: 
- "wrapper" (new default) can have title and description
- "boxed" can have columns
The schemas currently present on the server are handled by `convertLegacyUiOptions`, we need to think about how to handle these cases in the future. We might not remove `convertLegacyUiOptions` in the future, but just keep it for old sent forms (if we want to display them).

Forms improvements v4

---

next/clients/openapi-forms/api.ts
next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsList.tsx

As part of merging all of the legacy PRs a new option was added to forms endpoint - the new behaviour does not quite match with what is described in product docs, so we're not using it yet. Neither does out current behaviour btw, still keeping it unchanged until we get to this.
This needs to be deployed in sync with the form backend.

Update nest-forms-backedn OpenAPI - userCanEdit

---

next/frontend/utils/amplifyClient.ts
next/frontend/utils/amplifyServer.ts
next/pages/force-logout.tsx
next/pages/prihlasenie.tsx

Instead of just throwing a 500 on failed asserts, redirect to page which forces client-side code to clear cookies & local storage and log out.
Having a page such as force-logout isn't good practice, keeping it only temporarily until the present issue is resolved.

Force logout on assert

---

forms-shared/src/form-utils/validators.ts

It is not needed with npm, but needed with yarn.
So reverting.

Revert @ts-expect-error

---

nest-forms-backend/src/nases-consumer/nases-consumer.service.spec.ts
nest-forms-backend/src/nases-consumer/nases-consumer.service.ts
nest-forms-backend/src/rabbitmq-client/rabbitmq-client.service.ts

In [ginis.service](https://github.com/bratislava/konto.bratislava.sk/blob/a1444adf2fd2413c6eab76c0a1b129857aa51364/nest-forms-backend/src/ginis/ginis.service.ts#L440) we throw error if the formDefinition for the form is not slovenskoSkGeneric. For this reason, we should only send to ginis such forms, which fulfill this. Along with this change there is one naming change.

fix: publish to ginis only if it is slovensko sk generic

---

.github/workflows/deploy.yml
.github/workflows/validate-and-build.yml

It seems to fail if not supported characters are used in branch name, I decided to use commit it as id instead.
Example pipeline: https://github.com/bratislava/konto.bratislava.sk/actions/runs/9741337544/job/26880345369

Use sha instead of head_ref or ref_name in pipelines

---

forms-shared/src/form-utils/validators.ts
forms-shared/tests/form-utils/validators.ts
forms-shared/tests/schemas.ts

https://rjsf-team.github.io/react-jsonschema-form/docs/usage/validation/#using-the-raw-ajv-instance

Remove Ajv extraction as it is already supported by the library itself

---

nest-forms-backend/Dockerfile
next/Dockerfile

added missing `/` after `/app` to make it `/app/`. This makes sure that `forms-shared/app` is copied to desired location without `/app` folder. Also on `prod` build we were missing `/app/` path.
on dev it worked fine and nest-forms-backend and next were deployed https://github.com/bratislava/konto.bratislava.sk/actions/runs/10010292745

Added missing slash to properly mount forms-shared on nest-forms-backend and next

---

forms-shared/src/generator/functions.ts
forms-shared/src/generator/helpers.ts
forms-shared/tests/form-utils/defaultFormState.ts
forms-shared/tests/form-utils/fileUtils.ts
forms-shared/tests/form-utils/omitExtraData.ts
forms-shared/tests/summary-json/getSummaryDisplayValue.tsx
forms-shared/tests/summary-renderer/validateSummary.ts

- Add comment for removeUndefinedValues
- Wrap all generated schemas in `removeUndefinedValues`, fields were generated with `schema` and `uiSchema` as functions, this makes the generated output unserializable, so it needed to be reworked to return simple JSON
- Replace usages

Generator functions refactor

---

forms-shared/src/definitions/devFormDefinitions.ts
forms-shared/src/definitions/formDefinitionTypes.ts
forms-shared/src/definitions/formDefinitions.ts
forms-shared/src/slovensko-sk/generateXml.ts
forms-shared/src/slovensko-sk/xmlBuilder.ts
forms-shared/tests/definitions/formDefinitions.ts
nest-forms-backend/src/convert/convert.controller.ts
nest-forms-backend/src/convert/convert.service.ts
nest-forms-backend/src/convert/dtos/form.dto.ts
nest-forms-backend/src/convert/errors/convert.errors.dto.ts
nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts
next/clients/openapi-forms/api.ts
next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
next/frontend/hooks/useFormExportImport.tsx
next/generateOpenApiClient.ts

Commit by commit
- Moves Žiadost o nájomné byvanie to production forms, but with `(TESTOVACIA VERZIA)` in form name
- Creates new `newGovernmentXml` flag that is used in `ConvertService` to use new XML generation for this form
- Refactored `convertJsonToXmlV2` to have form id required 
- there was no use case where it was not provided
- it is needed, because new XMLs need files to be generated (which are not possible to fetch without form id)
- it matches how PDFs are generated
- form slug can be removed from request payload
- this is TODO version and will be refactored soon (when we migrate all the forms to the new XML)

Release Žiadost o nájomné byvanie

---

nest-forms-backend/Dockerfile

Playwright must be installed after node_modules are copied

---

nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts

Fixes an error when the technical account jwt token could not be generated.
https://stackoverflow.com/questions/74131595/error-error1e08010cdecoder-routinesunsupported-with-google-auth-library

fix: use fixed private key format

---

forms-shared/src/slovensko-sk/extractJson.ts

When downloading form from Slovensko.sk user interface, `xmlns:xsi` is not present.

Remove xmlns:xsi from BaseFormXml in extractJson

---

forms-shared/src/sharepoint/mappings/ziadostONajomnyByt.ts
forms-shared/tests/sharepoint/__snapshots__/getValuesForSharepoint.ts.snap

There was an error when sending income data to sharepoint for other members of the household. In the path there was extra `ziadatelZiadatelka`.

fix: correct mapping in sharepoint for other members of household

---

forms-shared/src/definitions/formDefinitionTypes.ts
forms-shared/src/definitions/formDefinitions.ts
nest-forms-backend/src/ginis/ginis.service.ts

Checked with @vidriduch , ginis-automation service should allow this. This should be the correct production assignment, we want to test it in advance and then revert until monday.

Change Ginis assignee, allow ginis org name without person

---

forms-shared/src/form-utils/getObjectFieldInfo.ts
forms-shared/src/summary-json/SummaryXmlForm.tsx
next/components/forms/FormPage.tsx
next/components/forms/FormProviders.tsx
next/components/forms/FormsPlayground.tsx
next/components/forms/segments/FormCalculator/FormCalculator.tsx
next/components/forms/segments/FormModals/FormModals.tsx
next/components/forms/signer/useFormSignature.tsx
next/components/forms/steps/Summary/SummaryAdditionalInfo.tsx
next/components/forms/steps/Summary/SummaryDetails.tsx
next/components/forms/steps/Summary/useFormSummary.tsx
next/components/forms/useFormData.tsx
next/components/forms/useFormFileUpload.tsx
next/components/forms/useFormRedirects.tsx
next/components/forms/useFormSend.tsx
next/components/forms/useFormState.tsx
next/components/forms/widget-wrappers/BAObjectFieldTemplate.tsx
next/frontend/hooks/useFormExportImport.tsx
next/package-lock.json
next/package.json
next/pages/forms-playground.ts

- Install @monaco-editor/react
- Extract getting info about object fields to getObjectFieldInfo
- Display form step title and description in object template instead of form wrapper (this is needed for playground and is generally a better place to do so)
- Extract formData from useFormState to its own hook useFormData, this is needed in playground in order to not mock the whole useFormState object
- Export FormFileUploadContext to be mocked
- Create FormsPlayground

Form playground

---

clamav/kubernetes/base/deployment.yml
clamav/kubernetes/envs/Dev/config.json
clamav/kubernetes/envs/Prod/config.json
clamav/kubernetes/envs/Staging/config.json

On staging kubernetes for last clamav deploymen we got this error:
`0/5 nodes are available: 1 Insufficient memory, 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 3 Insufficient cpu.`
I added option to configure resources per cluster. Now on dev and staging are resources on `best-effort` with is done by setting a value to `0`

Configure resources limits for clamav

---

.github/workflows/deploy.yml

Currently, the naming of `forms-shared` images is based solely on `github.sha`. This means that our Harbor retention rules only apply to the 10 most recent images. Since we have a high-traffic pipeline run repository, it can happen that the specific `forms-shared` image, which was built at the beginning of the deployment pipeline run, will not be available, for example, to `next`, which is the last component to build. For example it can take 25 minutes from the start of the pipeline until the `next` part is built.
This PR extends the `forms-shared` image name to include `github.ref_name`, which will contain deployment tags (`dev*`, `staging*`, `prod*`). With that we trigger harbor retention rules for prod, master and the required image will be present. Since this change only affects the …

Updated forms-shared image naming

---

.github/workflows/deploy.yml
.github/workflows/validate-and-build.yml
.github/workflows/validate-forms-shared-konto.yml

After the shared pipelines were updated with the [fetch-depth option](https://github.com/bratislava/github-actions/pull/31), we can now use it in Konto. We are setting the fetch-depth to 1, which means we are pulling only the current commit, not the entire commit history. This will even more speed up pipeline runs.

added fetch-depth option

---

.github/dependabot.yml

This PR updates permissions on pipelines to make it possible run when invoked by dependabot.

Allowing dependabot to run pipelines

---

.github/workflows/deploy.yml
.github/workflows/validate-and-build.yml

This update addresses the issue of hitting Docker Hub pull limits by ensuring authentication during Docker pulls. Logging in will increase our rate limits, preventing future disruptions.
**Important**
Please merge this PR only if the change from the following pipeline update has already been propagated:
[bratislava/github-actions#33](https://github.com/bratislava/github-actions/pull/33)

Docker.com login for pipelines

---

forms-shared/tests/slovensko-sk/slovenskoSkForm.ts
forms-shared/tests/summary-pdf/renderSummaryPdf.ts
forms-shared/tests/tax-form/taxForm.ts

Temporarily increase PDF timeout until we reduce the number of screenshot tests.

Temporarily increase PDF timeout

---

nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
nest-forms-backend/src/utils/global-services/mailgun/mailgun.service.ts

Adds a file `potvrdenie.pdf` with the filled-in data to the confirmation email to user after sending OLO form.

Send confirmation pdf as attachment to user in OLO forms

---

next/frontend/utils/ginis.ts

DossierId was always incorrect, prefer showing nothing.
In general, the detail page needs some love - this fixes incorrect data and prevents from showing data people from rental housing don't want to show - as well as assuming other clerks outside of taxes department will want to keep their emails and contacts hidden. But otherwise keeps the status quo until this page is looked at.

Filter GINIS details in form detail page

---

nest-forms-backend/src/nases/utils-services/tokens.nases.service.spec.ts
nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts

This seems to be the problem with the failed tax form from couple of weeks ago. After removing whitespace UPVS accepts.
I've taken a fair bit of time thinking about where this removal should happen. Settled on "just before sending", but other legit options are:
- right when we get the data from the signer
- before the data is stored in db
For now I've figured I'd like to see unchanged data in db, so that if anything else (weird) starts coming from the signer we can investigate more easily.

Clean whitespace from base64 form data before sending

---

next/components/forms/useFormSend.tsx

It was not possible to send the form beforehand as unauthenticated, this strips the requirement of being logged in.

Change access token policy when sending form

---

nest-tax-backend/package-lock.json
nest-tax-backend/package.json

In production there was the axios package missing. That is because all of the packages using axios were just as `devDependencies`.

Fix: install axios in tax backend

---

nest-tax-backend/prisma/migrations/20241104081100_create_indices_remove_table/migration.sql
nest-tax-backend/prisma/schema.prisma
nest-tax-backend/src/admin/admin.service.ts
nest-tax-backend/src/noris/noris.service.ts
nest-tax-backend/src/payment/payment.service.ts
nest-tax-backend/src/tasks/tasks.service.ts
nest-tax-backend/src/tax/tax.service.ts
nest-tax-backend/src/utils/subservices/dtos/gpwebpay.dto.ts

- create indices on `Tax` and `TaxPayment` tables
- remove `LoadingPaymentsFromNoris` table, since it is not used anymore
- create enum `PaymentStatus`, instead of using hardcoded strings
- handle eslint disables in AdminService (no await in loop and cognitive complexity)

Make task queries more effective

---

nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts

See comment in code. I'm not sure if this is the reason, but I couldn't find any erroneous logs for the forms linked below. I assume it's because if the function below throws it does not get logged anywhere ? But the user should correctly receive error, so they should not end up with "success" message, but we are blind to what happened. This should locally fix that until we roll better logging.
A few erroneous forms [here](https://metabase.bratislava.sk/question#eyJuYW1lIjoiRm9ybXMiLCJkZXNjcmlwdGlvbiI6IkEgYmFzaWMgbG9vayBhdCB0aGUgRm9ybXMgdGFibGUiLCJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsImRhdGFiYXNlIjo2LCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOiJjYXJkX18xNzkiLCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLCJGb3JtVHlwZSIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sInByaXpuYW5pZSBrIGRhbmkgeiBuZWhudXRlbG5vc3RpIl0sW …

Handle errors in sendMessageNases

---

nest-forms-backend/.env.example
nest-forms-backend/kubernetes/envs/Dev/.env
nest-forms-backend/kubernetes/envs/Prod/.env
nest-forms-backend/kubernetes/envs/Staging/.env
nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
nest-forms-backend/src/utils/global-services/mailgun/mailgun.service.ts

Instead of constant `zakazka` use different emails for each OLO form.

Send OLO mails from different mail addresses

---

nest-forms-backend/src/forms/forms.module.ts
nest-forms-backend/src/forms/subservices/forms-task.subservice.ts

Creates a task which runs daily and removed all forms (along with its files), which are:
1. Older than 1 week
2. Are in `DRAFT` state
3. Have `null` data
Tested locally and it works, however it should be watched on staging and the first run will contain many forms.

Daily task to remove old draft empty forms

---

tests/.yarnrc.yml

My editor keeps adding this line to package.json whenever I run npm i anywhere in the project.
```
"packageManager": "yarn@1.22.19+sha1.4ba7fc5c6e704fce2066ecbfb0b0d8976fe62447"
```
Claude AI says this is because .yarnrc exists in the project. Indeed, when I removed the file it stopped happening.
Don't know if anyone else is encountering these issues, either way, removing the file should be safe as we're using npm on all sub-projects.

Remove .yarnrc.yml file

---

nest-forms-backend/src/forms/subservices/forms-task.subservice.ts

There was a problem with deleting by IN: ids
`Assertion violation on the database: too many bind variables in prepared statement, expected maximum of 32767, received 39460`
This should fix the problem.

Do not delete old forms by ID

---

nest-forms-backend/prisma/migrations/20241115091118_migrate_processing_to_finished/migration.sql
nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
nest-forms-backend/src/nases-consumer/subservices/__test__/webhook.subservice.spec.ts
nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
nest-forms-backend/src/nases-consumer/subservices/webhook.subservice.ts

- for email and webhook forms uses `FINISHED` as the final state instead of `PROCESSING`
- migrates all such forms (email and webhook with `PROCESSING`) to `FINISHED` state.

Use FINISHED state as final for email and webhook forms

---

nest-tax-backend/src/admin/admin.service.ts

Instead of calling aggregate each time in the loop, call it just once outside of the loop and then retrieve the records by id.

Use only one aggregate call for payments import

---

next/components/forms/signer/useFormSignature.tsx
next/components/forms/steps/Summary/SummaryDetails.tsx
next/components/forms/useFormContext.tsx

Causes flickering of form summary because it relies on `useEffect` - https://usehooks-ts.com/react-hook/use-is-client. Use [much better](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/ssr/src/SSRProvider.tsx) `useIsSSR` instead.

useIsSSR instead of useIsClient

---

.github/dependabot.yml

Turns off dependabot alerts for the next package, should open only security updates (as mentioned in [github documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit))

Open only security dependabot PRs in next

---

nest-forms-backend/.env.example
nest-forms-backend/docker-compose.yml
nest-forms-backend/package.json

- update docker-compose so that ports don't collide with setups for other projects (planning to do something similar for other nest-* services in this repo as well)
- update .env.example to contain everything needed for sending forms from local dev to fix NASES apart from few secrets, listed on top of the file. Match ports used in docker-compose
- add missing volta config in nest-forms-backend

.env.example and docker-compose updates for local nest-forms development

---

nest-city-account/.eslintrc
nest-city-account/src/user-verification/utils/subservice/__tests__/verification.subservice.spec.ts
nest-city-account/src/user-verification/utils/subservice/verification.subservice.ts

If a person has record in RFO, but has do identity cards, magproxy returns `{}` instead of `[]`, thus the iteration errors.

Do not error if magproxy returns empty object instead of array

---

.github/workflows/comment-after-release.yml

Uses existing action - https://github.com/marketplace/actions/release-commenter
The code seems concise enough to toy with if we decide we need more - https://github.com/apexskier/github-release-commenter/blob/main/src/index.ts
GH token is automatically provided by github, when running in CI, so I'm being lazy and want to test "in production" instead of locally - that is, did not run this yet, but if you're ok with it I'd merge and see what it does.

Comment on related PRs and Issues after release

---

nest-tax-backend/src/admin/dtos/requests.dto.ts
nest-tax-backend/src/noris/noris.queries.ts
nest-tax-backend/src/noris/noris.service.ts
nest-tax-backend/src/tasks/tasks.service.ts

Fixes the automatic task which imports payments for taxes, so it will import payments even for taxes from past years (basically all unpaid).
The first query was tested on production database, duration of it running was almost the same as the query before. Noris queries were tested on staging Noris, they work, however `years[]` must not be empty.

Fix: Import payments even for taxes from past years

---

nest-forms-backend/src/nases/nases.service.ts

We no longer do SENDING_TO_NASES. That allows users to resend while the form is still in flight to NASES. The assumption/oversight was that this operation would either complete or fail quickly, but it's not always the case. We're always sending to nases with the same uuid so we can only send once (this is good, prevents duplicates) - but if the person resends during an in-flight request they may get failed sending on the sunsequent attempt which overwrites the state in db to DRAFT & NASES_SEND_ERROR - and end them stuck in this state forever despite the form being already successful from the initial attempt.
Setting to queued is not super nice, but it prevents resends and displays correctly in FE. The assumption with this change is that we need to rework these states either way.

Form status to QUEUED before eid nases send

---

nest-tax-backend/src/admin/__tests__/admin.service.spec.ts
nest-tax-backend/src/admin/admin.controller.ts
nest-tax-backend/src/admin/admin.service.ts
nest-tax-backend/src/admin/dtos/requests.dto.ts
nest-tax-backend/src/auth/guards/cognito.guard.ts
nest-tax-backend/src/noris/noris.queries.ts
nest-tax-backend/src/noris/noris.service.ts
nest-tax-backend/src/noris/noris.types.ts
nest-tax-backend/src/utils/functions/__test__/birthNumber.spec.ts
nest-tax-backend/src/utils/functions/birthNumber.ts
nest-tax-backend/src/utils/subservices/cityaccount.subservice.ts

Creates two endpoints in tax backend for modifying delivery methods for users in Noris.
1. First is for updating delivery methods for users which have city account, that is setting if they want to receive tax notification by Edesk, Post, or directly via city account.
2. Second is for removing delivery methods for given user, used when an account is deactivated, to set their delivery methods to default value (and mark that this person does not have an city account anymore)
Also this PR removes the `create-tax-payers` endpoint, which is not used anymore.
A small detail is moving the logic of adding slashes to birth numbers to separate function `addSlashToBirthNumber`.
This has been tested locally, with the non-production Noris `cvicna_magistrat`.

Endpoint for changing delivery methods in tax backend

---

next/frontend/utils/ginis.ts
next/pages/moje-ziadosti/[ziadost].tsx

Show at least something while we do not have ginis `ssl` ("spisová služba") endpoint. Without it we can load neither the id/dossierId data, or the `gin` service owner info, which requires owner id from `ssl` service.

Fake GINIS data while ssl endpoint does not work

---

nest-tax-backend/src/utils/middlewares/logger.ts

Use response `statusCode` and `statusMessage` after the rest of the request pipeline has run, so that updated values are used.

Fix responseCode in logs, when an error was thrown.

---

nest-tax-backend/src/admin/__tests__/admin.service.spec.ts
nest-tax-backend/src/admin/admin.service.ts
nest-tax-backend/src/noris/__tests__/noris.service.spec.ts
nest-tax-backend/src/noris/noris.service.ts

Instead of one connection for each update of delivery method create just one connection and perform multiple Requests on it.

Fix: do not open many connections when updating delivery methods

---

nest-tax-backend/src/admin/admin.service.ts
nest-tax-backend/src/noris/noris.dto.ts
nest-tax-backend/src/noris/noris.queries.ts

When importing taxes from Noris, import their payments right away so there won't be a delay where the tax could be marked as unpaid, even if it is already paid.
The noris queries were tested and are working correctly, the removed SELECT fields were not used anywhere in the code, so they are not necessary to be selected. It was important for `NorisPaymentsDto` to be a subset of `NorisTaxPayersDto`, so after selecting the taxes (including their payments), we can only call the function which adds the payments into database.

Feat: import taxes with their payments

---

forms-shared/src/signer/signerData.ts
forms-shared/src/slovensko-sk/generateXml.ts
forms-shared/src/slovensko-sk/renderXmlSummary.tsx
forms-shared/src/summary-email/SummaryEmail.tsx
forms-shared/src/summary-email/renderSummaryEmail.tsx
forms-shared/src/summary-json/getSummaryJson.tsx
forms-shared/src/summary-json/getSummaryJsonBrowser.ts
forms-shared/src/summary-json/getSummaryJsonNode.ts
forms-shared/src/summary-pdf/SummaryPdf.tsx
forms-shared/src/summary-pdf/renderSummaryPdf.tsx
forms-shared/src/summary-renderer/SummaryRenderer.tsx
forms-shared/src/summary-renderer/validateSummary.ts
forms-shared/src/summary/summary.ts
forms-shared/tests/signer/signerData.ts
forms-shared/tests/slovensko-sk/slovenskoSkForm.ts
forms-shared/tests/summary-email/renderSummaryEmail.ts
forms-shared/tests/summary-json/getSummaryJson.ts
forms-shared/tests/summary-pdf/renderSummaryPdf.ts
forms-shared/tests/summary-renderer/validateSummary.ts
nest-forms-backend/src/convert/convert.service.ts
nest-forms-backend/src/forms/forms.errors.enum.ts
nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
nest-forms-backend/src/nases/nases.service.spec.ts
nest-forms-backend/src/nases/nases.service.ts
nest-forms-backend/src/signer/signer.service.ts
next/components/forms/steps/Summary/SummaryDetails.tsx
next/components/forms/steps/Summary/useFormSummary.tsx
next/components/forms/useFormState.tsx
next/frontend/utils/getInitialSummaryJson.ts

This change https://github.com/bratislava/konto.bratislava.sk/pull/2079 generated `formSummary` when form is sent. It wasn't used until now. In this PR we use persisted `formSummary` for sent forms which allows us to change JSON schema (and bump versions whenever we want = versioning). Without this, the summary (PDF, email) will be still generated on the fly. This assures that the summary will be generate once (during send) and the will be stable 100%. E.g. when when remove some field and we download PDF for form that contained the field, it will still be in summary.
Also, previously we validated the form data for sent form (naturally they contained 0 errors and they weren't displayed - as XML summery renderer doesn't support showing them anyway). This was changed to only accept …

1850 Generate form summary from persisted `formSummary` from DB in sent forms

---

nest-forms-backend/src/nases/nases.service.ts

I attached `formSummary` after it is send (which fails becaue XML/PDF generation is missing `formSummary`). Now it is added to form before the send.

Fix summary update when sending form through eID

---

docker-compose.yml
strapi/.gitignore
strapi/config/middlewares.ts
strapi/config/server.ts

- set the postgres volume locally - before, it was accessible globally and therefore overwritten by other strapi local instances
- minor cleanup

Minor cleanup in strapi configs

---

forms-shared/Dockerfile
forms-shared/test-utils/fetchSlovenskoSkFormMetadata.ts
forms-shared/tests/slovensko-sk/slovenskoSkForm.ts

> Dataset elektronických formulárov
> 
> Od februára 2025 je každý deň automatizovane zverejňovaný dataset, ktorý obsahuje zoznam všetkých elektronických formulárov a to v dvoch formátoch:.json, .csv. . Zverejnený je na stránke Národný katalóg otvorených dát ako [Zoznam MEF](https://data.slovensko.sk/datasety/654ddfde-14bd-4237-99ef-cddda467fc40).
> 
> Dátová štruktúra datasetu je popísaná v [Návode na registráciu a správu formulárov v module elektronických formulárov](https://www.slovensko.sk/_img/CMS4/Navody/navod_registracia_eform_ovm.pdf)  v kapitole „Zverejňovanie zoznamu formulárov – dataset“  na strane 36.
> 
> Dataset obsahuje aj URL linky na jednotlivé formuláre na statickom úložisku formulárov. S jeho pomocou je možné automaticky vyskladať odkaz buď na každú súčasť …

Use JSON endpoint to fetch Slovensko.sk metadata

---

forms-shared/src/definitions/formDefinitions.ts
nest-forms-backend/src/utils/global-services/mailer/mailgun.constants.ts

Adds a different feedback link to emails for TSB. After merging, it should be changed in mailgun template as well.

Feat: add feedback links to tsb mails

---

.github/dependabot.yml

Instead of opening dependabot PRs on Mondays as default, open them on Sundays so they will not use up all of our pipeline resources.
Unfortunately, dependabot does not support YAML anchors/aliases :') https://github.com/dependabot/dependabot-core/issues/1582 som even though it is copy-pasted 7 times, we cannot use some shared value for each package.

Set dependabot to run on sundays

---

forms-shared/src/definitions/formDefinitionTypes.ts
forms-shared/src/definitions/formDefinitions.ts
nest-forms-backend/src/ginis/subservices/ginis-tasks.subservice.ts

I would like to avoid:
- having form specific hardcoded behaviour all over the code - I strongly prefer flags even for these one-off features
- the previous logic relied on the processing state, however this now filters only Slovensko.sk forms in `slugsToProcess`

Implement skipGinisStateUpdate flag

---

nest-tax-backend/src/admin/admin.controller.ts
nest-tax-backend/src/admin/admin.service.ts
nest-tax-backend/src/admin/dtos/requests.dto.ts
nest-tax-backend/src/admin/utils/testing-tax-mock.ts
nest-tax-backend/src/auth/guards/not-production.guard.ts

Creates an endpoint, which mocks the creation of a tax for testing purposes. Most of the values are mocked, however, some like tax amount can be set for each testing tax.
Furthermore creates an endpoint to delete these testing taxes.
Will create some documentation on how to do this testing, since it is necessary to not have any conflict with the real data.

Endpoint for creating and deleting testing taxes

---

nest-tax-backend/kubernetes/base/deployment.yml
nest-tax-backend/kubernetes/envs/Dev/kustomization.yml
nest-tax-backend/kubernetes/envs/Dev/secrets/email.secret.yml
nest-tax-backend/kubernetes/envs/Prod/kustomization.yml
nest-tax-backend/kubernetes/envs/Prod/secrets/email.secret.yml
nest-tax-backend/kubernetes/envs/Staging/kustomization.yml
nest-tax-backend/kubernetes/envs/Staging/secrets/email.secret.yml
nest-tax-backend/src/utils/subservices/email.subservice.ts

- Added secrets for email subservice
- Added documentation about why we use AWS SES instead of Mailgun as suggested by @lukasbabula.

Add email secrets and documentation

---

nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts

This behavior is requested by Lubo (ref. reg.). Since we are sending the message to ourselves, we can see it in inbox just fine, no need for it to have in outbox, and it clutters the outbox too much.
If there is any other sender, we still want to save the message to their outbox.

Skip nases outbox if we are sending the message to ourselves

---

nest-forms-backend/src/ginis/ginis.service.ts

If ginis throws an error, the file stream needs to be recreated, otherwise all subsequent retries only encounter read error rendering the retry mechanic useless.

Recreate file stream for each ginis upload file retry

---

nest-forms-backend/src/ginis/subservices/ginis-api.service.ts

According to the ginis documentation for SSL `pridat-soubor`:
**`Jmeno-souboru`**: string; Max. 254, Min. 1
**`Popis-souboru`**: string; Max. 50, Min. 0
**`Podrobny-popis-souboru`**: string; Max. 254, Min. 1

Implement ginis file upload string length restrictions

---

nest-tax-backend/src/noris/noris.queries.ts

Taxes without "pohladavka" should not be imported, as they still can be changed

FIX: Do not import taxes without "pohladavka"

---

nest-tax-backend/src/admin/admin.service.ts

Instead of invoking `findFirst` for each element just to check existence, use one `findMany` call and process accordingly.

use findMany instead of findFirst when possible

---

nest-forms-backend/src/auth-v2/services/cognito-user.service.ts

Create form was throwing `Invalid user attributes received from Cognito.` because it received an empty object without `Expose`.

Fix CognitoUserService

---

.github/dependabot.yml

Several eslint updates are dependent on each other and failing separately needing manual resolution. If grouped, this should not be problem anymore. Also, there are many and frequent eslint updates cluttering PRs and needing separate reviews and wasting pipeline resources.

Group eslint dependabot updates for backends

---

nest-city-account/prisma/migrations/20250623100430_create_fields_for_marking_deceased_users/migration.sql
nest-city-account/prisma/schema.prisma
nest-city-account/src/admin/admin.controller.ts
nest-city-account/src/admin/admin.service.ts
nest-city-account/src/admin/dtos/requests.admin.dto.ts
nest-city-account/src/admin/dtos/responses.admin.dto.ts
nest-city-account/src/prisma/prisma.service.ts
nest-city-account/src/user-verification/utils/subservice/database.subservice.ts
nest-city-account/src/user/utils/subservice/database.subservice.ts
nest-city-account/src/utils/subservices/cognito.subservice.ts
nest-city-account/src/utils/subservices/tasks.subservice.ts

This pull request introduces functionality to handle marking user accounts as deceased. The updates include:
- Addition of a method to mark user accounts as deceased.
- Implementation of an API endpoint for marking accounts as deceased.
- Updates to the Prisma schema to include fields for indicating deceased status.

Mark user accounts as deceased

---

strapi/config/env/production/plugins.ts
strapi/kubernetes/base/.env

```
2025-07-02 13:03:48.332 | at async /home/node/app/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22 |  
-- | -- | --
  |   | 2025-07-02 13:03:48.332 | at async /home/node/app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:121:14 |  
  |   | 2025-07-02 13:03:48.332 | at async /home/node/app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:90:28 |  
  |   | 2025-07-02 13:03:48.332 | at async region (/home/node/app/node_modules/@smithy/config-resolver/dist-cjs/index.js:142:30) |  
  |   | 2025-07-02 13:03:48.332 | at async /home/node/app/node_modules/@smithy/property-provider/dist-cjs/index.js:135:20 |  
  |   | 2025-07-02 13:03:48.332 | at async coalesceProvider (/home/node/app/node_modules/@smithy/property-provider/dist-cjs/index.js:124:18) |  
  |   | …
```

Add missing region

---

nest-tax-backend/prisma/migrations/20250702110129_move_tax_employee_to_tax_payer/migration.sql
nest-tax-backend/prisma/migrations/20250702141655_rename_tax_employee_to_tax_administrator/migration.sql
nest-tax-backend/prisma/schema.prisma
nest-tax-backend/src/admin/admin.service.ts
nest-tax-backend/src/admin/utils/__tests__/admin.helper.spec.ts
nest-tax-backend/src/admin/utils/admin.helper.ts
nest-tax-backend/src/admin/utils/testing-tax-mock.ts
nest-tax-backend/src/tax/dtos/response.tax.dto.ts
nest-tax-backend/src/tax/tax.service.ts
next/pages/dane-a-poplatky/index.tsx
openapi-clients/tax/api.ts

- renames tax employee to tax **administrator**, to be consistent with frontend
- instead of one tax administrator for each tax, there will be one for each tax payer, so each tax payer will have just one administrator
- adds the information about the administrator to the response with tax details, makes the frontend ready to use this data instead of determining the tax administrator by the first letter of the surname
- add admin.helper tests

885 - Save tax employee info for each tax payer from Noris

---

nest-forms-backend/src/ginis/ginis.service.spec.ts
nest-forms-backend/src/ginis/ginis.service.ts

After several weeks of observing ginis errors using the new ginis API approach to form processing (that replaced previous ginis automation approach), two changes are in order:
1. failure of attachment upload shall be retried indefinitely
- new API allows file upload even if the owner of the ginis document changes and it no longer belongs to us
- errors experienced were (with one exception) always cleared after simply retrying the same flow with no changes
- the one exception was a file with `|` in the name, that has been mitigated since then on the minio side
2. failure of submission assignment shall not be retried
- occurs when submission is already assigned to someone else manually (i.e. the owner of the document changes and it no longer belongs to us)
- this is the last step on the …

Adjust ginis service processing

---

docs/runbook/formulare-support.md
nest-forms-backend/prisma/migrations/20250718100858_remove_sending_to_nases_form_state/migration.sql
nest-forms-backend/prisma/schema.prisma
next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsList.tsx
next/components/styleguide/showcases/MyApplicationsCardShowCase.tsx
next/frontend/hooks/useFormStateComponents.tsx
next/public/locales/sk/account.json
openapi-clients/forms/api.ts

https://github.com/bratislava/private-konto.bratislava.sk/issues/596
Removed the unused state `SENDING_TO_NASES` from the whole codebase, as well as from the database on staging and prod.

Remove form state SENDING_TO_NASES

---

nest-city-account/src/bloomreach/bloomreach.service.ts
nest-city-account/src/magproxy/magproxy.service.ts
nest-city-account/src/user-verification/utils/subservice/verification.subservice.ts
nest-clamav-scanner/src/forms-client/forms-client.service.ts
nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts

Since openapi-clients use different instances of `AxiosError`, the comparison using `instanceof` will return `false`, even though it is of type `AxiosError`, but different instance. Because of this we should use `isAxiosError` function from axios.
Also changes `in` to `includes`.

Fix: use isAxiosError instead of comparing instances

---

nest-tax-backend/prisma/migrations/20250813082922_make_installment_order_required/migration.sql
nest-tax-backend/prisma/schema.prisma
nest-tax-backend/src/admin/utils/__tests__/admin.helper.spec.ts
nest-tax-backend/src/admin/utils/admin.helper.ts
nest-tax-backend/src/tax/tax.service.ts
nest-tax-backend/src/tax/utils/__tests__/unified-tax.util.spec.ts
nest-tax-backend/src/tax/utils/unified-tax.util.ts

This pull request involves:
- Changing the `order` field type from optional `String` to `Integer` in the `TaxInstallment` table.
- Modifying related logic and method calls to accommodate the type change.
- Adding and populating the `order` property within the system based on identifiable text patterns for tax installments.

Convert `order` field in tax installments to integer

---

nest-forms-backend/src/nases-consumer/nases-consumer.module.ts
nest-forms-backend/src/nases-consumer/nases-consumer.service.spec.ts
nest-forms-backend/src/nases-consumer/nases-consumer.service.ts
nest-forms-backend/src/nases/nases.errors.enum.ts
nest-forms-backend/src/nases/nases.module.ts
nest-forms-backend/src/nases/nases.service.spec.ts
nest-forms-backend/src/nases/nases.service.ts
nest-forms-backend/src/utils/constants/error.alerts.ts

https://github.com/bratislava/private-konto.bratislava.sk/issues/79
- moved `sendToNasesAndUpdateState` to NasesService instead of NasesConsumer;
- removed generating pdf and sending to Ginis from `sendToNasesAndUpdateState`, so that the function will only send to Nases and accordingly update the form;
- instead of returning boolean, it now returns nothing, and in case of an error it throws. This is for better error handling.

79 - Refactor sendToNasesAndUpdateState

---

nest-city-account/src/admin/admin.service.ts
nest-city-account/src/admin/dtos/responses.admin.dto.ts
nest-tax-backend/prisma/migrations/20250715085147_save_delivery_method_for_tax_payer/migration.sql
nest-tax-backend/prisma/schema.prisma
nest-tax-backend/src/admin/__tests__/admin.service.spec.ts
nest-tax-backend/src/admin/admin.service.ts
nest-tax-backend/src/admin/utils/testing-tax-mock.ts
nest-tax-backend/src/noris/__tests__/noris.service.spec.ts
nest-tax-backend/src/noris/noris.dto.ts
nest-tax-backend/src/noris/noris.queries.ts
nest-tax-backend/src/noris/noris.service.ts
nest-tax-backend/src/noris/noris.types.ts
nest-tax-backend/src/noris/utils/__tests__/noris.helper.spec.ts
nest-tax-backend/src/noris/utils/noris.helper.ts
nest-tax-backend/src/utils/types/types.prisma.ts
openapi-clients/city-account/api.ts
openapi-clients/city-account/base.ts

https://github.com/bratislava/private-konto.bratislava.sk/issues/866
We must save `POSTAL` as `EDESK` in Noris, as it was requested by tax administrators.
No migration has to be performed, since new delivery methods will be updated next year, and there will correctly be EDESK in place of POSTAL.

866 save postal as edesk in noris

---

nest-tax-backend/prisma/migrations/20250925103129_add_tax_type_enum/migration.sql
nest-tax-backend/prisma/schema.prisma
nest-tax-backend/src/noris/subservices/noris-tax.subservice.ts
nest-tax-backend/src/tax/dtos/response.tax.dto.ts
nest-tax-backend/src/tax/tax.service.ts
openapi-clients/tax/api.ts

As a preparation for multiple types of tax in database, this PR adds an enum of type of tax. So far all taxes will have type `DZN`, and nothing from the functionality changes, however this work is needed to be on the same track of development.

Add type of tax enum to database
